# Generated by Django 5.2.10 on 2026-01-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
