# Generated by Django 5.2.10 on 2026-01-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0002_part_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stock_balances', to='avv.location'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lot_stock_balances', to='avv.stocklot'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_stock_balances', to='avv.part'),
        ),
    ]
