# Generated by Django 5.2.10 on 2026-01-25 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0004_remove_part_uom_unitofmeasure'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='uom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uom_parts', to='avv.unitofmeasure'),
        ),
    ]
