# Generated by Django 5.2.10 on 2026-01-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0005_part_uom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unitofmeasure',
            options={'ordering': ['is_system', 'serial_number', 'code']},
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='serial_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
