# Generated by Django 5.2.10 on 2026-01-25 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_companysettings_adblue_tank_volume_l_and_more'),
        ('avv', '0006_alter_unitofmeasure_options_unitofmeasure_is_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitofmeasure',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_units_of_measure', to='app.company'),
        ),
    ]
