# Generated by Django 5.2.10 on 2026-01-25 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0007_alter_unitofmeasure_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
