# Generated by Django 5.2.10 on 2026-01-26 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0009_issuedocument_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuedocument',
            name='status',
            field=models.CharField(choices=[('ISSUED', 'Issued'), ('CONFIRMED', 'Confirmed')], default='ISSUED', max_length=16),
        ),
    ]
