# Generated by Django 5.2.10 on 2026-01-28 13:25

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_companysettings_adblue_tank_volume_l_and_more'),
        ('avv', '0011_workorder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to='app.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_work_order_parts', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_work_order_issues', to='avv.location')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_work_order_issues', to='avv.part')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_issues', to='avv.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['work_order'], name='avv_workord_work_or_d9c567_idx'), models.Index(fields=['part'], name='avv_workord_part_id_a9f987_idx')],
            },
        ),
    ]
