# Generated by Django 5.2.10 on 2026-01-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0009_alter_country_label_alter_country_value'),
        ('avv', '0012_workorderissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderissue',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_work_order_issue', to='abb.currency'),
        ),
        migrations.AddField(
            model_name='workorderissue',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
