# Generated by Django 5.2.10 on 2026-01-28 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0016_remove_workorder_labor_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='description',
            new_name='problem_description',
        ),
    ]
