# Generated by Django 5.2.10 on 2026-01-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0018_workorder_driver_alter_workorder_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
