# Generated by Django 5.2.10 on 2026-01-28 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0019_workorder_started_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklot',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='currency',
        ),
    ]
