# Generated by Django 5.2.10 on 2026-01-28 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0009_alter_country_label_alter_country_value'),
        ('avv', '0020_remove_stocklot_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_stock_lot', to='abb.currency'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_stock_movements', to='abb.currency'),
        ),
    ]
