# Generated by Django 5.2.10 on 2026-01-28 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0021_stocklot_currency_stockmovement_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderissue',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lot_work_order_issues', to='avv.stocklot'),
        ),
    ]
