# Generated by Django 5.2.10 on 2026-01-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0022_workorderissue_lot'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
