# Generated by Django 5.2.10 on 2026-01-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0023_workorder_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='service_type',
            field=models.CharField(choices=[('INTERNAL', 'Internal service'), ('THIRD_PARTY', 'Third-party workshop')], default='INTERNAL', max_length=20),
        ),
    ]
