# Generated by Django 5.2.10 on 2026-01-29 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0066_alter_vehicle_weight_capacity'),
        ('avv', '0024_workorder_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='third_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='third_party_work_order', to='att.contact'),
        ),
    ]
