# Generated by Django 5.2.10 on 2026-01-29 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0027_worktype_workorderworkline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderworkline',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_line_units', to='avv.unitofmeasure'),
        ),
    ]
