# Generated by Django 5.2.10 on 2026-01-30 11:00

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0031_workorderattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderattachment',
            name='file',
            field=models.FileField(upload_to=abb.utils.image_upload_path),
        ),
    ]
