# Generated by Django 5.2.10 on 2026-02-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avv', '0034_partattachment_partbrand_part_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partbrand',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
