# Generated by Django 5.2.10 on 2026-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(default=dict),
        ),
    ]
