# Generated by Django 5.2.10 on 2026-02-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bbo', '0002_notification_payload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='title',
        ),
    ]
