# Generated by Django 5.2.10 on 2026-02-13 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbo', '0003_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('document_expiry', 'Document Expiry'), ('birthday', 'Birthday')], max_length=50),
        ),
    ]
