# Generated by Django 5.2.9 on 2025-12-07 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_date_of_birth_team_userpermission'),
        ('att', '0002_rename_payload_companyvehicle_add_consumption_with_load_and_more'),
        ('axx', '0001_initial'),
        ('ayy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_documents', to='att.companyvehicle'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_for_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='company_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_image_uploads', to='att.companyvehicle'),
        ),
        migrations.AddIndex(
            model_name='imageupload',
            index=models.Index(fields=['company_vehicle'], name='ayy_imageup_company_b8d11d_idx'),
        ),
    ]
