# Generated by Django 5.2.9 on 2025-12-13 05:48

import abb.utils
import ayy.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_warehouse'),
        ('axx', '0003_ctr_series_inv_tor_exp_and_more'),
        ('ayy', '0002_document_company_vehicle_documenttype_is_for_vehicle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_obj', models.FileField(blank=True, null=True, upload_to=ayy.utils.dynamic_upload_path)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='imageupload',
            name='ayy_imageup_user_id_e1d790_idx',
        ),
        migrations.RemoveIndex(
            model_name='imageupload',
            name='ayy_imageup_load_id_ebce90_idx',
        ),
        migrations.RemoveIndex(
            model_name='imageupload',
            name='ayy_imageup_company_54a6ad_idx',
        ),
        migrations.RemoveIndex(
            model_name='imageupload',
            name='ayy_imageup_company_b8d11d_idx',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='company_vehicle',
        ),
        migrations.RemoveField(
            model_name='imageupload',
            name='user',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_imageuploads', to='app.company'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file_obj',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_imageuploads', to='axx.load'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='uf',
            field=models.CharField(default=abb.utils.hex_uuid, max_length=36),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_fileuploads', to='app.company'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='inv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_fileuploads', to='axx.inv'),
        ),
    ]
