# Generated by Django 5.2.9 on 2025-12-16 16:59

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('att', '0011_alter_vehiclebrand_options_and_more'),
        ('axx', '0003_ctr_series_inv_tor_exp_and_more'),
        ('ayy', '0003_fileupload_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('action', models.CharField(blank=True, choices=[('loading', 'Loading'), ('unloading', 'Unloading'), ('parking', 'Parking'), ('clearance', 'Customs stop')], max_length=20, null=True)),
                ('date_load', models.DateTimeField(blank=True, null=True)),
                ('time_load_min', models.DateTimeField(blank=True, null=True)),
                ('time_load_max', models.DateTimeField(blank=True, null=True)),
                ('zip_load', models.CharField(blank=True, max_length=20, null=True)),
                ('city_load', models.CharField(blank=True, max_length=50, null=True)),
                ('shipperinstructions1', models.CharField(blank=True, max_length=250, null=True)),
                ('shipperinstructions2', models.CharField(blank=True, max_length=250, null=True)),
                ('palletexchange', models.BooleanField(blank=True, default=False, null=True)),
                ('tail_lift', models.BooleanField(blank=True, default=False, null=True)),
                ('dangerousgoods', models.BooleanField(blank=True, default=False, null=True)),
                ('dangerousgoods_class', models.CharField(blank=True, max_length=30, null=True)),
                ('temp_control', models.BooleanField(blank=True, default=False, null=True)),
                ('temp_control_details', models.CharField(blank=True, max_length=40, null=True)),
                ('order', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_entries', to='att.contact')),
                ('country_load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_load_entries', to='abb.country')),
                ('ctr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_ctrs', to='axx.ctr')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_invs', to='axx.inv')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_loads', to='axx.load')),
                ('tor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_tors', to='axx.tor')),
            ],
            options={
                'verbose_name': 'Entry',
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('pieces', models.CharField(blank=True, max_length=10, null=True)),
                ('weight', models.CharField(blank=True, max_length=10, null=True)),
                ('ldm', models.CharField(blank=True, max_length=10, null=True)),
                ('volume', models.CharField(blank=True, max_length=10, null=True)),
                ('dims', models.CharField(blank=True, max_length=150, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrydetails', to='ayy.entry')),
            ],
        ),
    ]
