# Generated by Django 5.2.9 on 2025-12-17 05:01

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('app', '0008_usersettings'),
        ('att', '0011_alter_vehiclebrand_options_and_more'),
        ('axx', '0003_ctr_series_inv_tor_exp_and_more'),
        ('ayy', '0004_entry_detail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_details', to='ayy.entry'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('comment', models.CharField(blank=True, max_length=400, null=True)),
                ('ctr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctr_comments', to='axx.ctr')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_comments', to='axx.inv')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_comments', to='axx.load')),
                ('tor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tor_comments', to='axx.tor')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_comments', to='axx.trip')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='changed_by_histories', to=settings.AUTH_USER_MODEL)),
                ('ctr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctr_histories', to='axx.ctr')),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_histories', to='axx.exp')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inv_histories', to='axx.inv')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_histories', to='axx.load')),
                ('tor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tor_histories', to='axx.tor')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_histories', to='axx.trip')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Histories',
                'ordering': ['-date_registered'],
            },
        ),
        migrations.CreateModel(
            name='ItemForItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('serial_number', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('is_fuel', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_item_for_item_costs', to='app.company')),
            ],
            options={
                'verbose_name': 'Item for itemcost',
                'verbose_name_plural': 'Items for itemcost',
            },
        ),
        migrations.CreateModel(
            name='ItemForItemInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('description', models.CharField(max_length=150)),
                ('um', models.CharField(blank=True, choices=[('pc', 'Piece'), ('kg', 'Kg'), ('t', 'Tonne'), ('cbm', 'CBM'), ('lt', 'Litre')], default='pc', max_length=20, null=True)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, choices=[(21, '21%'), (20, '20%'), (19, '19%'), (11, '11%'), (9, '9%'), (5, '5%'), (0, '0%')], default=0, null=True)),
                ('vat_type', models.CharField(blank=True, choices=[('normal', 'Normal'), ('reduced', 'Reduced'), ('zero', 'Zero'), ('sfdd', 'SFDD'), ('sdd', 'SDD'), ('reverse_charge', 'Reverse charge'), ('exempt', 'Exempt')], default='zero', max_length=20, null=True)),
                ('exemption_reason', models.CharField(blank=True, choices=[('vatex-eu-g', 'VATEX-EU-G'), ('vatex-eu-ic', 'VATEX-EU-IC'), ('vatex-eu-o', 'VATEX-EU-O'), ('vatex-eu-ae', 'VATEX-EU-AE')], max_length=20, null=True)),
                ('is_sale', models.BooleanField(default=True)),
                ('archived', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_item_for_item_invs', to='app.company')),
            ],
            options={
                'verbose_name': 'Item for iteminv',
                'verbose_name_plural': 'Items for iteminv',
            },
        ),
        migrations.CreateModel(
            name='ItemInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('ctr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctr_iteminvs', to='axx.ctr')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='currency_iteminvs', to='abb.currency')),
                ('exp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exp_iteminvs', to='axx.exp')),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='iteminv_invs', to='axx.inv')),
                ('item_for_item_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_for_item_cost_iteminvs', to='ayy.itemforitemcost')),
                ('item_for_item_inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_for_item_inv_iteminvs', to='ayy.itemforiteminv')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='load_iteminvs', to='axx.load')),
                ('tor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tor_iteminvs', to='axx.tor')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_iteminvs', to='axx.trip')),
            ],
            options={
                'verbose_name': 'Item inv',
                'verbose_name_plural': 'Items inv',
            },
        ),
        migrations.CreateModel(
            name='RouteSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('rs_number', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_issue', models.DateTimeField()),
                ('date_departure', models.DateTimeField(blank=True, null=True)),
                ('date_arrival', models.DateTimeField(blank=True, null=True)),
                ('km_departure', models.FloatField(blank=True, null=True)),
                ('km_arrival', models.FloatField(blank=True, null=True)),
                ('fuel_start', models.FloatField(blank=True, null=True)),
                ('fuel_end', models.FloatField(blank=True, null=True)),
                ('notes_date', models.CharField(blank=True, max_length=100, null=True)),
                ('notes_km', models.CharField(blank=True, max_length=100, null=True)),
                ('notes_fuel', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('stops', models.JSONField(blank=True, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_route_sheets', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_route_sheets', to='app.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='currency_route_sheets', to='abb.currency')),
                ('end_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='ending_route_sheets', to='att.contact')),
                ('start_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='starting_route_sheets', to='att.contact')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='trip_route_sheets', to='axx.trip')),
                ('vehicle_tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_tractor_route_sheets', to='att.vehiclecompany')),
                ('vehicle_trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vehicle_trailer_route_sheets', to='att.vehiclecompany')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('vat', models.PositiveIntegerField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_itemcosts', to='app.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='currency_itemcosts', to='abb.currency')),
                ('item_for_item_cost', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='item_for_item_cost_itemcosts', to='ayy.itemforitemcost')),
                ('route_sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_sheet_itemcosts', to='ayy.routesheet')),
            ],
            options={
                'verbose_name': 'Item cost',
                'verbose_name_plural': 'Items cost',
            },
        ),
        migrations.CreateModel(
            name='RouteSheetDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='route_sheet_links', to=settings.AUTH_USER_MODEL)),
                ('route_sheet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_links', to='ayy.routesheet')),
            ],
            options={
                'verbose_name': 'Route sheet driver',
                'verbose_name_plural': 'Route sheet drivers',
                'unique_together': {('route_sheet', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='routesheet',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='route_sheets', through='ayy.RouteSheetDriver', to=settings.AUTH_USER_MODEL),
        ),
    ]
