# Generated by Django 5.2.9 on 2025-12-17 07:58

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usersettings'),
        ('axx', '0003_ctr_series_inv_tor_exp_and_more'),
        ('ayy', '0005_alter_detail_entry_comment_history_itemforitemcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_issue', models.DateTimeField(blank=True, null=True)),
                ('place_issue', models.CharField(blank=True, max_length=200, null=True)),
                ('place_load', models.CharField(blank=True, max_length=200, null=True)),
                ('place_unload', models.CharField(blank=True, max_length=200, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('list_of_documents', models.CharField(blank=True, max_length=200, null=True)),
                ('special_agreement', models.CharField(blank=True, max_length=100, null=True)),
                ('payment', models.CharField(blank=True, max_length=100, null=True)),
                ('cod', models.CharField(blank=True, max_length=100, null=True)),
                ('cod_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_cmrs', to='app.company')),
                ('load', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cmr', to='axx.load')),
            ],
            options={
                'verbose_name': 'cmr',
                'verbose_name_plural': 'cmrs',
                'ordering': ['-date_created'],
                'constraints': [models.UniqueConstraint(fields=('company', 'number'), name='unique_company_cmr_number')],
            },
        ),
    ]
