# Generated by Django 5.2.9 on 2025-12-18 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0012_person_contact_alter_person_site'),
        ('ayy', '0006_cmr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='contact',
        ),
        migrations.AddField(
            model_name='entry',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_entries', to='att.contact'),
        ),
    ]
