# Generated by Django 5.2.9 on 2025-12-19 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usersettings_base_doc_lang_usersettings_ctr_columns_and_more'),
        ('ayy', '0007_remove_entry_contact_entry_shipper'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMRStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=20)),
                ('number_from', models.PositiveIntegerField()),
                ('number_to', models.PositiveIntegerField()),
                ('received_at', models.DateField()),
                ('total_count', models.PositiveIntegerField(editable=False)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmr_batches', to='app.company')),
            ],
            options={
                'unique_together': {('company', 'series', 'number_from', 'number_to')},
            },
        ),
    ]
