# Generated by Django 5.2.9 on 2025-12-19 09:11

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0008_cmrstockbatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmrstockbatch',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36),
        ),
    ]
