# Generated by Django 5.2.9 on 2025-12-19 14:55

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('app', '0010_categorygeneral'),
        ('att', '0012_person_contact_alter_person_site'),
        ('ayy', '0009_cmrstockbatch_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmrstockbatch',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cmr_stock', to='app.company'),
        ),
        migrations.AlterField(
            model_name='cmrstockbatch',
            name='notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.CreateModel(
            name='AuthorizationStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('series', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('price', models.SmallIntegerField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_authorizations', to='app.categorygeneral')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_authorizations_stock', to='app.company')),
                ('countries', models.ManyToManyField(related_name='authorization_countries', to='abb.country')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_authorizations', to='att.vehiclecompany')),
            ],
            options={
                'unique_together': {('company', 'number', 'category')},
            },
        ),
    ]
