# Generated by Django 5.2.9 on 2025-12-19 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_typegeneral'),
        ('ayy', '0010_alter_cmrstockbatch_company_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='authorizationstockbatch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='authorizationstockbatch',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='type_authorizations', to='app.typegeneral'),
        ),
        migrations.AlterUniqueTogether(
            name='authorizationstockbatch',
            unique_together={('type', 'company', 'number', 'category')},
        ),
    ]
