# Generated by Django 5.2.9 on 2025-12-19 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_typegeneral'),
        ('ayy', '0011_alter_authorizationstockbatch_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authorizationstockbatch',
            old_name='category',
            new_name='category_authorization',
        ),
        migrations.RenameField(
            model_name='authorizationstockbatch',
            old_name='countries',
            new_name='countries_authorization',
        ),
        migrations.RenameField(
            model_name='authorizationstockbatch',
            old_name='type',
            new_name='type_authorization',
        ),
        migrations.RenameField(
            model_name='authorizationstockbatch',
            old_name='vehicle',
            new_name='vehicle_authorization',
        ),
        migrations.AlterUniqueTogether(
            name='authorizationstockbatch',
            unique_together={('type_authorization', 'company', 'number', 'category_authorization')},
        ),
    ]
