# Generated by Django 5.2.9 on 2025-12-20 04:14

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_name_categorygeneral_label_and_more'),
        ('ayy', '0012_rename_category_authorizationstockbatch_category_authorization_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTIRStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('series', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField(blank=True, null=True)),
                ('price', models.SmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ctir_stock', to='app.company')),
            ],
            options={
                'unique_together': {('company', 'number')},
            },
        ),
    ]
