# Generated by Django 5.2.9 on 2025-12-20 04:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0013_ctirstockbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctirstockbatch',
            name='number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ctirstockbatch',
            name='received_at',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ctirstockbatch',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
