# Generated by Django 5.2.9 on 2025-12-20 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0014_alter_ctirstockbatch_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationstockbatch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ctirstockbatch',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
