# Generated by Django 5.2.9 on 2025-12-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0015_alter_authorizationstockbatch_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorizationstockbatch',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
