# Generated by Django 5.2.9 on 2025-12-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0016_alter_authorizationstockbatch_series'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='shipper',
        ),
    ]
