# Generated by Django 5.2.9 on 2025-12-22 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0014_alter_contactsite_address_site_and_more'),
        ('ayy', '0017_remove_entry_shipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='shipper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipper_entries', to='att.contactsite'),
        ),
    ]
