# Generated by Django 5.2.9 on 2025-12-23 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0018_entry_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmrstockbatch',
            name='series',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
