# Generated by Django 5.2.9 on 2025-12-24 11:21

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0004_statustype_code_statustypetranslation'),
        ('app', '0018_user_is_archived'),
        ('att', '0022_contactsite_comment1_contactsite_comment2'),
        ('ayy', '0019_alter_cmrstockbatch_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageLiability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_damage_liabilities', to='app.company')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_damage_liabilities', to='abb.currency')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_damage_liabilities', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DamagePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_at', models.DateField()),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('salary_deduction', 'Salary deduction'), ('bank_transfer', 'Bank transfer')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('liability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liability_damage_payments', to='ayy.damageliability')),
            ],
        ),
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_damage_reports', to='app.company')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_damage_reports', to='att.vehiclecompany')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('damage_type', models.CharField(blank=True, choices=[('scratch', 'Scratch'), ('dent', 'Dent'), ('crack', 'Crack'), ('broken', 'Broken'), ('missing', 'Missing'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(blank=True, choices=[('minor', 'Minor'), ('medium', 'Medium'), ('severe', 'Severe')], max_length=20)),
                ('part', models.CharField(help_text='e.g. Front bumper, Left door, Trailer side panel', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_repaired', models.BooleanField(default=False)),
                ('repaired_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_damages', to='app.company')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_vehicle_damages', to='ayy.damagereport')),
            ],
        ),
        migrations.AddField(
            model_name='damageliability',
            name='damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_damage_liabilities', to='ayy.vehicledamage'),
        ),
    ]
