# Generated by Django 5.2.9 on 2025-12-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0020_damageliability_damagepayment_damagereport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledamage',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
