# Generated by Django 5.2.9 on 2025-12-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0021_vehicledamage_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damageliability',
            name='damage',
        ),
        migrations.AddField(
            model_name='damageliability',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_damage_liabilities', to='ayy.damagereport'),
        ),
    ]
