# Generated by Django 5.2.9 on 2025-12-25 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0022_remove_damageliability_damage_damageliability_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_damage_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
