# Generated by Django 5.2.9 on 2025-12-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0023_damagereport_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledamage',
            name='part',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
