# Generated by Django 5.2.9 on 2025-12-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0022_contactsite_comment1_contactsite_comment2'),
        ('ayy', '0024_alter_vehicledamage_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='damage_report_type',
            field=models.CharField(blank=True, choices=[('vehicle', 'Vehicle'), ('goods', 'Goods')], max_length=20),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_damage_reports', to='att.vehiclecompany'),
        ),
    ]
