# Generated by Django 5.2.9 on 2025-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0025_damagereport_damage_report_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagereport',
            name='damage_report_type',
            field=models.CharField(blank=True, choices=[('vehicle_damage', 'Vehicle'), ('goods_damage', 'Goods')], max_length=20),
        ),
    ]
