# Generated by Django 5.2.9 on 2025-12-28 12:57

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('ayy', '0026_alter_damagereport_damage_report_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColliType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(blank=True, max_length=20)),
                ('ldm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_colli_types', to='app.company')),
            ],
            options={
                'verbose_name': 'Colli Type',
                'verbose_name_plural': 'Colli Types',
                'ordering': ['code'],
                'unique_together': {('code', 'company')},
            },
        ),
    ]
