# Generated by Django 5.2.9 on 2025-12-28 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0027_collitype'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='colli_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='colli_type_details', to='ayy.collitype'),
        ),
    ]
