# Generated by Django 5.2.9 on 2025-12-28 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('ayy', '0028_detail_colli_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collitype',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_colli_types', to='app.company'),
        ),
    ]
