# Generated by Django 5.2.9 on 2025-12-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0029_alter_collitype_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collitype',
            name='ldm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
