# Generated by Django 5.2.9 on 2025-12-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0031_auto_last_existing'),
    ]


operations = []
