# Generated by Django 5.2.9 on 2025-12-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0031_collitype_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='is_stackable',
            field=models.BooleanField(default=False),
        ),
    ]
