# Generated by Django 5.2.9 on 2025-12-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0031_collitype_serial_number'),
        ('ayy', '0032_entry_is_stackable'),
    ]

    operations = [
    ]
