# Generated by Django 5.2.9 on 2025-12-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0033_remove_vehiclecompany_brand_and_more'),
        ('ayy', '0033_merge_20251231_0715'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='entry',
                    name='is_stackable',
                    field=models.BooleanField(default=False),
                ),]), migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='authorizationstockbatch',
                    name='vehicle_authorization',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='vehicle_authorizations', to='att.vehicle'),
                ), ]), migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='damagereport',
                    name='vehicle',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='vehicle_damage_reports', to='att.vehicle'),
                ),]), migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='document',
                    name='company_vehicle',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='company_vehicle_documents', to='att.vehicle'),
                ), ]), migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='routesheet',
                    name='vehicle_tractor',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                            related_name='vehicle_tractor_route_sheets', to='att.vehicle'),
                ),]), migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='routesheet',
                    name='vehicle_trailer',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT,
                                            related_name='vehicle_trailer_route_sheets', to='att.vehicle'),
                ), ]),
    ]
