# Generated by Django 5.2.9 on 2026-01-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0034_entry_is_stackable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collitype',
            name='description',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
