# Generated by Django 5.2.9 on 2026-01-03 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0035_collitype_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemforiteminv',
            old_name='archived',
            new_name='is_archived',
        ),
        migrations.AddField(
            model_name='itemforitemcost',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemforiteminv',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
