# Generated by Django 5.2.9 on 2026-01-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0036_rename_archived_itemforiteminv_is_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemforitemcost',
            name='is_card',
            field=models.BooleanField(default=False),
        ),
    ]
