# Generated by Django 5.2.9 on 2026-01-05 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0024_load_date_signed_load_is_paid_load_is_signed'),
        ('ayy', '0037_itemforitemcost_is_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcost',
            name='route_sheet',
        ),
        migrations.AddField(
            model_name='itemcost',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_itemcosts', to='axx.trip'),
        ),
    ]
