# Generated by Django 5.2.9 on 2026-01-06 07:35

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0043_alter_emissionclass_options_and_more'),
        ('ayy', '0038_remove_itemcost_route_sheet_itemcost_trip'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_imageuploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_imageuploads', to='att.vehicle'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='file_obj',
            field=models.FileField(upload_to=abb.utils.image_upload_path),
        ),
    ]
