# Generated by Django 5.2.9 on 2026-01-07 06:58

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_usersettings_load_2_columns_and_more'),
        ('ayy', '0040_useremail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('code', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_email_templates', to='app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_email_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.CreateModel(
            name='EmailTemplateVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayy.emailtemplate')),
            ],
        ),
        migrations.CreateModel(
            name='EmailTemplateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=2)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_email_translations', to='ayy.emailtemplate')),
            ],
            options={
                'unique_together': {('template', 'language')},
            },
        ),
    ]
