# Generated by Django 5.2.9 on 2026-01-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0041_emailtemplate_emailtemplatevariable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplatetranslation',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='emailtemplatetranslation',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
