# Generated by Django 5.2.9 on 2026-01-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0042_alter_emailtemplatetranslation_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
