# Generated by Django 5.2.9 on 2026-01-08 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0044_maillabel_mailmessage'),
    ]

    operations = [

    ]
