# Generated by Django 5.2.9 on 2026-01-08 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0045_remove_maillabel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillabel',
            name='slug',
        ),
        migrations.AlterField(
            model_name='maillabel',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
