# Generated by Django 5.2.9 on 2026-01-08 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0048_migrate_maillabel_to_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailmessage',
            name='labels',
            field=models.ManyToManyField(related_name='messages', to='ayy.maillabelv2'),
        ),
        migrations.DeleteModel(
            name='MailLabel',
        ),
    ]
