# Generated by Django 5.2.9 on 2026-01-08 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0049_alter_mailmessage_labels_delete_maillabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='email_attachments/')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to='ayy.useremail')),
            ],
        ),
    ]
