# Generated by Django 5.2.9 on 2026-01-08 08:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0050_useremailattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremailattachment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailattachment',
            name='filename',
            field=models.CharField(default='my_file', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useremailattachment',
            name='size',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
