# Generated by Django 5.2.9 on 2026-01-09 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0051_useremailattachment_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='unique_field',
        ),
    ]
