# Generated by Django 5.2.9 on 2026-01-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0052_remove_imageupload_unique_field'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
