# Generated by Django 5.2.9 on 2026-01-10 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0053_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='damage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='damage_imageuploads', to='ayy.damagereport'),
        ),
    ]
