# Generated by Django 5.2.9 on 2026-01-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('app', '0028_typecost'),
        ('ayy', '0054_imageupload_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcost',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='country_itemscosts', to='abb.country'),
        ),
        migrations.AddField(
            model_name='itemcost',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemcost',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='type_itemscosts', to='app.typecost'),
        ),
    ]
