# Generated by Django 5.2.9 on 2026-01-17 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0055_itemcost_country_itemcost_date_itemcost_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcost',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_itemcosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
