# Generated by Django 5.2.9 on 2026-01-18 10:32

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0056_itemcost_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageZipToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('image_ufs', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
