# Generated by Django 5.2.9 on 2026-01-18 10:43

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0057_imageziptoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageziptoken',
            name='token',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
    ]
