# Generated by Django 5.2.9 on 2026-01-18 10:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0058_alter_imageziptoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageziptoken',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
