# Generated by Django 5.2.9 on 2026-01-23 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0059_imageziptoken_expires_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemforitemcost',
            options={'ordering': ['-is_system', 'serial_number', 'company', '-id'], 'verbose_name': 'Item for itemcost', 'verbose_name_plural': 'Items for itemcost'},
        ),
    ]
