# Generated by Django 5.2.10 on 2026-02-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0060_alter_itemforitemcost_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='insurance_deductible',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='damagereport',
            name='is_insured',
            field=models.BooleanField(default=False),
        ),
    ]
