# Generated by Django 5.2.10 on 2026-02-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0061_damagereport_insurance_deductible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='route_sheet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
