# Generated by Django 5.2.10 on 2026-02-04 04:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0062_damagereport_route_sheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenttype',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='document_name',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='is_for_vehicle',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='order',
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_document_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='name',
            field=models.CharField(default='Some name', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='code',
            field=models.CharField(default='some_code', max_length=50),
            preserve_default=False,
        ),
    ]
