# Generated by Django 5.2.10 on 2026-02-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0063_remove_documenttype_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='order',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
