# Generated by Django 5.2.10 on 2026-02-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0064_entry_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='document_type',
            field=models.CharField(blank=True, choices=[('invoice', 'Invoice'), ('order', 'Order'), ('act', 'Act of execution')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imageupload',
            name='source',
            field=models.CharField(choices=[('upload', 'User upload'), ('generated', 'System generated')], default='upload', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageupload',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final')], default='final', max_length=20),
            preserve_default=False,
        ),
    ]
