# Generated by Django 5.2.10 on 2026-02-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0065_imageupload_document_type_imageupload_source_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_doc',
            new_name='date_issued',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_num',
            new_name='document_number',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='doc_type',
            new_name='document_type',
        ),
        migrations.RemoveField(
            model_name='document',
            name='company_vehicle',
        ),
        migrations.RemoveField(
            model_name='document',
            name='doc_det',
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
