# Generated by Django 5.2.10 on 2026-02-08 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0066_rename_date_doc_document_date_issued_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='date_exp',
            new_name='date_expiry',
        ),
    ]
