# Generated by Django 5.2.10 on 2026-02-08 04:44

import abb.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0067_rename_date_exp_document_date_expiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='target',
            field=models.CharField(choices=[('user', 'User'), ('vehicle', 'Vehicle')], default='vehicle', max_length=20),
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_issued', models.DateTimeField(blank=True, null=True)),
                ('date_expiry', models.DateTimeField()),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
                ('notifications', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=abb.utils.default_notification_status_3, size=3)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_type_user_documents', to='ayy.documenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
