# Generated by Django 5.2.10 on 2026-02-08 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0068_documenttype_target_userdocument_delete_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='expiry_alert_days',
            field=models.PositiveIntegerField(default=0, help_text='Number of days before expiry to send alerts. 0 = no alerts.'),
        ),
    ]
