# Generated by Django 5.2.10 on 2026-02-08 05:50

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0069_documenttype_expiry_alert_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=abb.utils.image_upload_path),
        ),
    ]
