# Generated by Django 5.2.10 on 2026-02-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('att', '0070_alter_vehicledocument_uf'),
        ('axx', '0038_loadinv_cancelled_at'),
        ('ayy', '0070_userdocument_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cmrstockbatch',
            name='used_count',
        ),
        migrations.CreateModel(
            name='CMRHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_type', models.CharField(choices=[('COMPANY', 'Company'), ('CUSTOMER', 'Customer'), ('VEHICLE', 'Vehicle')], max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='att.contact')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='att.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CMRStockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, max_length=20, null=True)),
                ('number_from', models.PositiveIntegerField()),
                ('number_to', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(editable=False)),
                ('movement_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('CONSUMED', 'Consumed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='ayy.cmrstockbatch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_movements', to='ayy.cmrholder')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cmr_movements', to='axx.load')),
                ('to_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_movements', to='ayy.cmrholder')),
            ],
        ),
        migrations.AddConstraint(
            model_name='cmrholder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', False), ('customer__isnull', False), ('vehicle__isnull', False), _connector='OR'), models.Q(models.Q(('company__isnull', False), ('customer__isnull', False)), models.Q(('company__isnull', False), ('vehicle__isnull', False)), models.Q(('customer__isnull', False), ('vehicle__isnull', False)), _connector='OR', _negated=True)), name='cmrholder_exactly_one_fk'),
        ),
    ]
