# Generated by Django 5.2.10 on 2026-02-09 08:07

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('att', '0070_alter_vehicledocument_uf'),
        ('ayy', '0071_remove_cmrstockbatch_used_count_cmrholder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('card_type', models.CharField(choices=[('BANK', 'Bank card'), ('FUEL', 'Fuel card'), ('TOLL', 'Toll card')], max_length=20)),
                ('provider', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=50, unique=True)),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_cards', to='app.company')),
                ('current_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_employee_cards', to=settings.AUTH_USER_MODEL)),
                ('current_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_vehicle_cards', to='att.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='CardAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGN', 'Assign'), ('UNASSIGN', 'Unassign')], max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_assigned_cards', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_assigned_cards', to='att.vehicle')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_assignments', to='ayy.companycard')),
            ],
        ),
        migrations.AddConstraint(
            model_name='companycard',
            constraint=models.CheckConstraint(condition=models.Q(('current_employee__isnull', False), ('current_vehicle__isnull', False), _negated=True), name='card_only_one_current_holder'),
        ),
        migrations.AddConstraint(
            model_name='cardassignment',
            constraint=models.CheckConstraint(condition=models.Q(('employee__isnull', False), ('vehicle__isnull', False), _negated=True), name='card_assignment_one_target'),
        ),
    ]
