# Generated by Django 5.2.10 on 2026-02-09 16:13

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0072_companycard_cardassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmrstockmovement',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36),
        ),
    ]
