# Generated by Django 5.2.10 on 2026-02-11 09:11

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('ayy', '0073_cmrstockmovement_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companycard',
            name='provider',
        ),
        migrations.CreateModel(
            name='CardProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_card_providers', to='app.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'code'), name='unique_provider_code_per_company'), models.UniqueConstraint(fields=('company', 'name'), name='unique_provider_name_per_company'), models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('is_system', True)), models.Q(('company__isnull', False), ('is_system', False)), _connector='OR'), name='system_provider_company_logic')],
            },
        ),
    ]
