# Generated by Django 5.2.10 on 2026-02-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0074_remove_companycard_provider_cardprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='companycard',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_cards', to='ayy.cardprovider'),
        ),
    ]
