# Generated by Django 5.2.10 on 2026-02-21 05:42

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0075_companycard_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcost',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to=abb.utils.image_upload_path),
        ),
    ]
