# Generated by Django 5.2.10 on 2026-03-20 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0052_trip_km_end_driver_recorded_at_and_more'),
        ('ayy', '0076_itemcost_receipt_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_imageuploads', to='axx.trip'),
        ),
    ]
