# Generated by Django 5.2.10 on 2026-03-21 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_companysettings_broker_invoice_start_number'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('ayy', '0077_imageupload_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='customs_broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_broker_entries', to='att.contact'),
        ),
        migrations.AddField(
            model_name='entry',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_entries', to='app.loadwarehouse'),
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cmr', 'CMR'), ('comm_invoice', 'Commercial invoice'), ('pack_list', 'Packing list'), ('cust_declaration', 'Customs declaration'), ('other', 'Other'), ('invoice', 'Invoice'), ('order', 'Order'), ('act', 'Act of execution')], max_length=50, null=True),
        ),
    ]
