services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: xumma_backend
    command: uvicorn xumma.asgi:application --reload --reload-dir /app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    ports:
      - "8000:8000"
    # depends_on:
    #   - redis
    volumes:
      - .:/app
      - static_data:/app/staticfiles
      - ./media:/app/media
      - ./email_attachments:/email_attachments

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A xumma worker -l info
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app
      - media_data:/app/media

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A xumma beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env
    depends_on:
      - backend
    volumes:
      - .:/app
      - media_data:/app/media

volumes:
  static_data:
  media_data:
