FROM python:3.11.4

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH="${PYTHONPATH}:/app"

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    proj-data \
    proj-bin \
    wkhtmltopdf \
    fonts-dejavu \
    libxrender1 \
    libxext6 \
    libfontconfig1 \
    libfreetype6 \
    gettext \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV CPLUS_INCLUDE_PATH=/usr/include/gdal
ENV C_INCLUDE_PATH=/usr/include/gdal

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

CMD ["uvicorn", "xumma.asgi:application", "--host", "0.0.0.0", "--port", "8000"]