# Generated by Django 5.2.10 on 2026-02-22 06:13

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_image'),
        ('axx', '0046_trip_arrival_inspection_completed'),
        ('ayy', '0076_itemcost_receipt_file'),
        ('driver', '0002_drivertrackpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('parking', 'Parking'), ('custom', 'Custom')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_trip_stops', to='app.company')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_stops', to='ayy.entry')),
                ('load', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='load_stops', to='axx.load')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='axx.trip')),
            ],
            options={
                'ordering': ['order'],
                'indexes': [models.Index(fields=['trip', 'order'], name='driver_trip_trip_id_b52d23_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'trip', 'order'), name='unique_trip_stop_order')],
            },
        ),
    ]
