# Generated by Django 5.2.10 on 2026-02-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_tripstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='is_visible_to_driver',
            field=models.BooleanField(default=True),
        ),
    ]
