# Generated by Django 5.2.10 on 2026-02-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_tripstop_is_visible_to_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='is_visible_to_driver',
            field=models.BooleanField(default=False),
        ),
    ]
