# Generated by Django 5.2.10 on 2026-02-23 07:07

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_image'),
        ('driver', '0005_alter_tripstop_is_visible_to_driver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStopMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('type', models.CharField(choices=[('text', 'Text'), ('system', 'System'), ('status', 'Status change'), ('photo', 'Photo'), ('document', 'Document')], default='text', max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read_by_driver', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_trip_stop_messages', to='app.company')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_trip_stop_messages', to=settings.AUTH_USER_MODEL)),
                ('trip_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stop_messages', to='driver.tripstop')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trip_stop', 'created_at'], name='driver_trip_trip_st_276a36_idx')],
            },
        ),
    ]
