# Generated by Django 5.2.10 on 2026-02-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_tripstopmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstopmessage',
            name='is_read_by_dispatcher',
            field=models.BooleanField(default=False),
        ),
    ]
