# Generated by Django 5.2.10 on 2026-02-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_tripstopmessage_is_read_by_dispatcher'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tripstop',
            name='driver_trip_trip_id_b52d23_idx',
        ),
        migrations.AlterField(
            model_name='tripstop',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('arrived', 'Arrived'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
    ]
