# Generated by Django 5.2.10 on 2026-02-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_remove_tripstop_driver_trip_trip_id_b52d23_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstop',
            name='is_completed',
        ),
    ]
