# Generated by Django 5.2.10 on 2026-02-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_remove_tripstop_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripstop',
            name='type',
            field=models.CharField(choices=[('pickup', 'Pickup'), ('delivery', 'Delivery'), ('parking', 'Parking'), ('custom', 'Custom'), ('warehouse_in', 'Warehouse Unload'), ('warehouse_out', 'Warehouse Reload')], max_length=20),
        ),
    ]
