# Generated by Django 5.2.10 on 2026-03-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_alter_tripstop_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripstop',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='tripstop',
            name='lon',
        ),
    ]
