# Generated by Django 5.2.10 on 2026-03-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_remove_tripstop_lat_remove_tripstop_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripstop',
            name='km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
