# Generated by Django 5.2.9 on 2025-12-07 07:34

import abb.mixins
import abb.utils
import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abb', '0002_bodytype_exchangerate_incoterm_modetype_statustype'),
        ('app', '0004_user_date_of_birth_team_userpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('company_name', models.CharField(max_length=150, null=True, verbose_name='company_name')),
                ('alias_company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('is_same_address', models.BooleanField(default=False)),
                ('fiscal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_com', models.CharField(blank=True, max_length=30, null=True)),
                ('subscribed_capital', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('city_legal', models.CharField(blank=True, max_length=50, null=True)),
                ('address_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('county_legal', models.CharField(blank=True, max_length=10, null=True)),
                ('sect_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code_post', models.CharField(blank=True, max_length=20, null=True)),
                ('city_post', models.CharField(blank=True, max_length=50, null=True)),
                ('address_post', models.CharField(blank=True, max_length=100, null=True)),
                ('county_post', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('messanger', models.CharField(blank=True, max_length=100, null=True)),
                ('comment1', models.CharField(blank=True, max_length=500, null=True)),
                ('comment2', models.CharField(blank=True, max_length=500, null=True)),
                ('other', models.CharField(blank=True, max_length=200, null=True)),
                ('is_vat_payer', models.BooleanField(default=False)),
                ('is_vat_on_receipt', models.BooleanField(default=False)),
                ('contact_type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), default=abb.utils.get_contact_type_default, size=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_contacts', to='app.company')),
                ('country_code_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_code_legal_contacts', to='abb.country')),
                ('country_code_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_code_post_contacts', to='abb.country')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('iban_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=150)),
                ('bank_code', models.CharField(max_length=30)),
                ('bank_address', models.CharField(blank=True, max_length=250, null=True)),
                ('add_instructions', models.TextField(blank=True, max_length=700, null=True)),
                ('include_in_inv', models.BooleanField(blank=True, default=False, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_bank_accounts', to='app.company')),
                ('currency_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bankaccountscurrency', to='abb.currency')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_bank_accounts', to='att.contact')),
            ],
            options={
                'verbose_name': 'Bank account',
                'verbose_name_plural': 'Bank accounts',
            },
        ),
        migrations.CreateModel(
            name='ContactSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('name_site', models.CharField(max_length=255)),
                ('address_site', models.CharField(max_length=255)),
                ('city_site', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_sites', to='att.contact')),
                ('country_code_site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_code_sites', to='abb.country')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('payment_term_short', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_term_description', models.CharField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_terms', to='app.company')),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
            },
        ),
        migrations.CreateModel(
            name='TargetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('group_name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_target_groups', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('mobile', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=250, null=True)),
                ('is_driver', models.BooleanField(blank=True, default=False, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_persons', to='att.contactsite')),
                ('target_group', models.ManyToManyField(related_name='target_group_persons', to='att.targetgroup')),
            ],
            bases=(abb.mixins.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('reg_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('tractor', 'Tractor'), ('trailer', 'Trailer'), ('truck', 'Truck')], max_length=10, null=True)),
                ('payload', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_vehicle_units', to='att.contact')),
            ],
            options={
                'verbose_name': 'Vehicle Unit',
                'verbose_name_plural': 'Vehicle Units',
                'ordering': ['reg_number'],
            },
            bases=(abb.mixins.ProtectedDeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CompanyVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('reg_number', models.CharField(max_length=20)),
                ('vehicle_type', models.CharField(blank=True, choices=[('tractor', 'Tractor'), ('trailer', 'Trailer'), ('truck', 'Truck')], max_length=10, null=True)),
                ('payload', models.PositiveIntegerField(blank=True, null=True)),
                ('volume', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_units', to='app.company')),
            ],
            options={
                'verbose_name': 'Company Vehicle',
                'verbose_name_plural': 'Company Vehicles',
                'ordering': ['reg_number'],
                'constraints': [models.UniqueConstraint(fields=('company', 'reg_number'), name='unique_together company reg_number')],
            },
            bases=(abb.mixins.ProtectedDeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('company_name'), name='unique_together company company_name'),
        ),
        migrations.AddConstraint(
            model_name='vehicleunit',
            constraint=models.UniqueConstraint(fields=('contact', 'reg_number'), name='unique_together contact reg_number'),
        ),
    ]
