# Generated by Django 5.2.9 on 2025-12-07 08:44

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0002_bodytype_exchangerate_incoterm_modetype_statustype'),
        ('app', '0004_user_date_of_birth_team_userpermission'),
        ('att', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyvehicle',
            old_name='payload',
            new_name='add_consumption_with_load',
        ),
        migrations.RenameField(
            model_name='companyvehicle',
            old_name='volume',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='change_oil_interval',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='consumption_summer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='consumption_winter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='has_dgr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='has_l_paket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='has_sanitary_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='interval_taho',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='last_date_unload_taho',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='sell_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='tank_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='vehicle_body',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_body_company_vehicles', to='abb.bodytype'),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='vin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='volume_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='weight_capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyvehicle',
            name='reg_number',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='EmissionClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_code', models.CharField(max_length=20, unique=True)),
                ('class_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_emission_classes', to='app.company')),
            ],
            options={
                'verbose_name': 'Emission Class',
                'verbose_name_plural': 'Emission Classes',
                'ordering': ['-class_code'],
            },
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='emission_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emission_class_company_vehicles', to='att.emissionclass'),
        ),
        migrations.CreateModel(
            name='VehicleBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('brand_name', models.CharField(max_length=100, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_brands', to='app.company')),
            ],
            options={
                'verbose_name': 'Vehicle Brand',
                'verbose_name_plural': 'Vehicle Brands',
                'ordering': ['brand_name'],
            },
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='brand_company_vehicles', to='att.vehiclebrand'),
        ),
    ]
