# Generated by Django 5.2.9 on 2025-12-07 12:06

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('app', '0006_smtpsettings'),
        ('att', '0002_rename_payload_companyvehicle_add_consumption_with_load_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCEMTCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('order_number', models.PositiveSmallIntegerField(unique=True)),
                ('st', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_authorization_cemt_categories', to='app.company')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='AuthorizationCEMT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_expire', models.DateField()),
                ('fee_amount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('series', models.CharField(blank=True, max_length=20, null=True)),
                ('number', models.CharField(max_length=20)),
                ('is_standard_authorization', models.BooleanField(default=False)),
                ('is_cemt_authorization', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_authorization_cemts', to='app.company')),
                ('company_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_authorization_cemts', to='att.companyvehicle')),
                ('countries', models.ManyToManyField(related_name='countries_authorization_cemts', to='abb.country')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_authorization_cemts', to='att.authorizationcemtcategories')),
            ],
            options={
                'verbose_name': 'Authorization CEMT',
                'verbose_name_plural': 'Authorization CEMTs',
                'constraints': [models.UniqueConstraint(fields=('company', 'series', 'number'), name='unique_company_series_number')],
            },
        ),
    ]
