# Generated by Django 5.2.9 on 2025-12-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('att', '0003_authorizationcemtcategories_authorizationcemt'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorizationcemt',
            name='restricted_countries',
            field=models.ManyToManyField(related_name='restricted_countries_authorization_cemts', to='abb.country'),
        ),
        migrations.AddField(
            model_name='companyvehicle',
            name='is_service_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentterm',
            name='payment_term_days',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
