# Generated by Django 5.2.9 on 2025-12-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('app', '0008_usersettings'),
        ('att', '0005_term'),
        ('ayy', '0003_fileupload_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyVehicle',
            new_name='VehicleCompany',
        ),
        migrations.AlterModelOptions(
            name='vehiclecompany',
            options={'ordering': ['reg_number'], 'verbose_name': 'Vehicle Company', 'verbose_name_plural': 'Vehicles Company'},
        ),
    ]
