# Generated by Django 5.2.9 on 2025-12-14 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0006_rename_companyvehicle_vehiclecompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebrand',
            name='serial_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehiclecompany',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
