# Generated by Django 5.2.9 on 2025-12-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0007_vehiclebrand_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclebrand',
            old_name='active',
            new_name='is_active',
        ),
    ]
