# Generated by Django 5.2.9 on 2025-12-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0008_rename_active_vehiclebrand_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecompany',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vehicleunit',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('truck', 'Truck'), ('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=10, null=True),
        ),
    ]
