# Generated by Django 5.2.9 on 2025-12-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0009_alter_vehiclecompany_vehicle_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionclass',
            options={'ordering': ['code'], 'verbose_name': 'Emission Class', 'verbose_name_plural': 'Emission Classes'},
        ),
        migrations.RenameField(
            model_name='emissionclass',
            old_name='class_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='emissionclass',
            old_name='class_name',
            new_name='name',
        ),
    ]
