# Generated by Django 5.2.9 on 2025-12-14 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0010_alter_emissionclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclebrand',
            options={'ordering': ['name'], 'verbose_name': 'Vehicle Brand', 'verbose_name_plural': 'Vehicle Brands'},
        ),
        migrations.RenameField(
            model_name='vehiclebrand',
            old_name='brand_name',
            new_name='name',
        ),
    ]
