# Generated by Django 5.2.9 on 2025-12-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0011_alter_vehiclebrand_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='att.contact'),
        ),
        migrations.AlterField(
            model_name='person',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_persons', to='att.contactsite'),
        ),
    ]
