# Generated by Django 5.2.9 on 2025-12-22 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0012_person_contact_alter_person_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsite',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactsite',
            name='zip_code_site',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
