# Generated by Django 5.2.9 on 2025-12-22 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0004_statustype_code_statustypetranslation'),
        ('att', '0013_contactsite_lat_contactsite_lon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsite',
            name='address_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contactsite',
            name='country_code_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country_code_sites', to='abb.country'),
        ),
        migrations.AlterField(
            model_name='contactsite',
            name='name_site',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
