# Generated by Django 5.2.9 on 2025-12-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0016_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsite',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_sites', to='att.contact'),
        ),
    ]
