# Generated by Django 5.2.9 on 2025-12-24 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_user_is_archived'),
        ('att', '0017_alter_contactsite_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_sites', to='app.company'),
        ),
    ]
