# Generated by Django 5.2.9 on 2025-12-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0018_contactsite_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsite',
            name='name_site',
            field=models.CharField(default='Company name', max_length=255),
            preserve_default=False,
        ),
    ]
