# Generated by Django 5.2.9 on 2025-12-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0019_alter_contactsite_name_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
