# Generated by Django 5.2.9 on 2025-12-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0020_contactsite_date_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contactsite',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
