# Generated by Django 5.2.9 on 2025-12-24 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0021_contactsite_email_contactsite_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='comment1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='contactsite',
            name='comment2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
