# Generated by Django 5.2.9 on 2025-12-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0022_contactsite_comment1_contactsite_comment2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='archived',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='person',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
    ]
