# Generated by Django 5.2.9 on 2025-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0023_rename_archived_person_is_private_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentterm',
            name='payment_term_short',
            field=models.CharField(max_length=100),
        ),
    ]
