# Generated by Django 5.2.9 on 2025-12-29 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('att', '0024_alter_paymentterm_payment_term_short'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecompany',
            name='vehicle_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_category_company_vehicles', to='app.categorygeneral'),
        ),
    ]
