# Generated by Django 5.2.9 on 2025-12-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0026_vehiclecompany_vehicle_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecompany',
            name='km_initial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
