# Generated by Django 5.2.9 on 2025-12-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0027_vehiclecompany_km_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emissionclass',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='emissionclass',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
