# Generated by Django 5.2.9 on 2025-12-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0028_rename_name_emissionclass_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
