# Generated by Django 5.2.9 on 2025-12-30 14:16

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('att', '0029_alter_bankaccount_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSheetStockBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('series', models.CharField(blank=True, max_length=20, null=True)),
                ('number_from', models.PositiveIntegerField()),
                ('number_to', models.PositiveIntegerField()),
                ('received_at', models.DateField()),
                ('total_count', models.PositiveIntegerField(editable=False)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, max_length=1000)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_route_sheet_stock', to='app.company')),
            ],
            options={
                'unique_together': {('company', 'series', 'number_from', 'number_to')},
            },
        ),
        migrations.CreateModel(
            name='RouteSheetNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('number', models.CharField(max_length=30)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_route_sheet_number', to='app.company')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_route_sheet_numbers', to='att.routesheetstockbatch')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
    ]
