# Generated by Django 5.2.9 on 2025-12-31 05:15

import abb.mixins
import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('app', '0019_userprofile'),
        ('att', '0032_remove_vehiclecompany_brand_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[

                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='brand',
                ),

            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='company',
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='emission_class',
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='vehicle_body',
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='vehicle_category',
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='vehiclecompany',
                    name='vehicle_category_type',
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='routesheetstockbatch',
                    name='reserved_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='routesheetstockbatch',
                    name='route_sheet_status',
                    field=models.CharField(choices=[(
                        'free', 'Free'), ('reserved', 'Reserved'), ('used', 'Used')], default='free', max_length=10),
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='routesheetstockbatch',
                    name='used_at',
                    field=models.DateTimeField(blank=True, null=True),
                ),
            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Vehicle',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True,
                                                   primary_key=True, serialize=False, verbose_name='ID')),
                        ('uf', models.CharField(db_index=True,
                                                default=abb.utils.hex_uuid, max_length=36, unique=True)),
                        ('reg_number', models.CharField(max_length=50)),
                        ('vin', models.CharField(
                            blank=True, max_length=50, null=True)),
                        ('vehicle_type', models.CharField(blank=True, choices=[
                            ('truck', 'Truck'), ('tractor', 'Tractor'), ('trailer', 'Trailer')], max_length=10, null=True)),
                        ('date_registered', models.DateField(blank=True, null=True)),
                        ('tank_volume', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('consumption_summer', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('consumption_winter', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('add_consumption_with_load',
                         models.PositiveIntegerField(blank=True, null=True)),
                        ('change_oil_interval', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('buy_price', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('sell_price', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('km_initial', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('length', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('width', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('height', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('weight_capacity', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('volume_capacity', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('interval_taho', models.PositiveIntegerField(
                            blank=True, null=True)),
                        ('last_date_unload_taho', models.DateField(
                            blank=True, null=True)),
                        ('comment', models.CharField(
                            blank=True, max_length=500, null=True)),
                        ('has_dgr', models.BooleanField(default=False)),
                        ('has_sanitary_certificate',
                         models.BooleanField(default=False)),
                        ('has_l_paket', models.BooleanField(default=False)),
                        ('is_rented', models.BooleanField(default=False)),
                        ('is_service_vehicle', models.BooleanField(default=False)),
                        ('is_available', models.BooleanField(default=True)),
                        ('is_archived', models.BooleanField(default=False)),
                        ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                                    related_name='brand_vehicles', to='att.vehiclebrand')),
                        ('company', models.ForeignKey(blank=True, null=True,
                                                      on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle', to='app.company')),
                        ('emission_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                             related_name='emission_class_vehicles', to='att.emissionclass')),
                        ('vehicle_body', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                           related_name='vehicle_body_vehicles', to='abb.bodytype')),
                        ('vehicle_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                               related_name='vehicle_category_vehicles', to='app.categorygeneral')),
                        ('vehicle_category_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                                    related_name='vehicle_category_type_vehicles', to='app.typegeneral')),
                    ],
                    options={
                        'verbose_name': 'Vehicle Company',
                        'verbose_name_plural': 'Vehicles Company',
                        'ordering': ['reg_number'],
                    },
                    bases=(abb.mixins.ProtectedDeleteMixin, models.Model),
                ),

            ]),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='authorizationcemt',
                    name='company_vehicle',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                            related_name='company_vehicle_authorization_cemts', to='att.vehicle'),
                ),]),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddConstraint(
                    model_name='vehicle',
                    constraint=models.UniqueConstraint(
                        fields=('company', 'reg_number'), name='unique_together company reg_number'),
                ),
            ]),
    ]
