# Generated by Django 5.2.9 on 2025-12-31 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0033_remove_vehiclecompany_brand_and_more'),
        ('axx', '0016_trip_rs_number_alter_trip_vehicle_tractor_and_more'),
        ('ayy', '0034_entry_is_stackable_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VehicleCompany',
        ),
    ]
