# Generated by Django 5.2.9 on 2025-12-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0034_delete_vehiclecompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='contact_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_vehicles', to='att.contact'),
        ),
    ]
