# Generated by Django 5.2.9 on 2025-12-31 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0035_vehicle_contact_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='contact_by',
        ),
        # migrations.RemoveField(
        #     model_name='vehicle',
        #     name='contact',
        # ),
    ]
