# Generated by Django 5.2.9 on 2025-12-31 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('att', '0037_vehicle_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicles', to='app.company'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_vehicles', to='att.contact'),
        ),
    ]
