# Generated by Django 5.2.9 on 2025-12-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0039_alter_vehicle_options_vehicle_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['created_at'], 'verbose_name': 'Vehicle', 'verbose_name_plural': 'Vehicles'},
        ),
    ]
