# Generated by Django 5.2.9 on 2025-12-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0040_alter_vehicle_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='is_vat_on_receipt',
        ),
        migrations.AlterField(
            model_name='routesheetstockbatch',
            name='received_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
