# Generated by Django 5.2.9 on 2026-01-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0041_remove_contact_is_vat_on_receipt_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='is_service_vehicle',
            new_name='is_service',
        ),
    ]
