# Generated by Django 5.2.9 on 2026-01-04 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_usersettings_trip_loads_columns'),
        ('att', '0042_rename_is_service_vehicle_vehicle_is_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emissionclass',
            options={'ordering': ['-serial_number'], 'verbose_name': 'Emission Class', 'verbose_name_plural': 'Emission Classes'},
        ),
        migrations.AddField(
            model_name='emissionclass',
            name='serial_number',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emissionclass',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_emission_classes', to='app.company'),
        ),
        migrations.AlterUniqueTogether(
            name='emissionclass',
            unique_together={('serial_number', 'company')},
        ),
    ]
