# Generated by Django 5.2.9 on 2026-01-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0043_alter_emissionclass_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsite',
            name='language',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
