# Generated by Django 5.2.9 on 2026-01-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0044_contactsite_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
