# Generated by Django 5.2.9 on 2026-01-11 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('att', '0045_person_default'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaseSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_userbasesalary', to='abb.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_base_salaries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('user', 'valid_from'), name='unique_user_salary_start_date')],
            },
        ),
        migrations.CreateModel(
            name='UserDailyAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_per_day', models.DecimalField(decimal_places=2, max_digits=8)),
                ('applies_only_during_trip', models.BooleanField(default=True)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_allowances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('user', 'valid_from'), name='unique_user_daily_allowance_start')],
            },
        ),
        migrations.CreateModel(
            name='UserVehicleKmRateOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abb.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_km_rate_overrides', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rate_overrides', to='att.vehicle')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle', 'valid_from'), name='unique_user_vehicle_km_override')],
            },
        ),
        migrations.CreateModel(
            name='VehicleKmRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_km', models.DecimalField(decimal_places=3, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abb.currency')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='km_rates', to='att.vehicle')),
            ],
            options={
                'ordering': ['-valid_from'],
                'constraints': [models.UniqueConstraint(fields=('vehicle', 'valid_from'), name='unique_vehicle_km_rate_start')],
            },
        ),
    ]
