# Generated by Django 5.2.9 on 2026-01-11 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0046_userbasesalary_userdailyallowance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdailyallowance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_daily_allowances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uservehiclekmrateoverride',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_vehicle_km_rate_overrides', to=settings.AUTH_USER_MODEL),
        ),
    ]
