# Generated by Django 5.2.9 on 2026-01-11 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('att', '0047_alter_userdailyallowance_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdailyallowance',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='abb.currency'),
        ),
    ]
