# Generated by Django 5.2.9 on 2026-01-11 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0048_userdailyallowance_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclekmrate',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_km_rates', to='att.vehicle'),
        ),
    ]
