# Generated by Django 5.2.9 on 2026-01-13 12:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('att', '0050_userloadingpointrate_userunloadingpointrate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userloadingpointrate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from')), ('valid_to__isnull', True), _connector='OR'), name='loading_point_rate_valid_range'),
        ),
        migrations.AddConstraint(
            model_name='userunloadingpointrate',
            constraint=models.CheckConstraint(condition=models.Q(('valid_to__gte', models.F('valid_from')), ('valid_to__isnull', True), _connector='OR'), name='unloading_point_rate_valid_range'),
        ),
    ]
