# Generated by Django 5.2.9 on 2026-01-13 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0051_userloadingpointrate_loading_point_rate_valid_range_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloadingpointrate',
            name='amount_per_point',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='userunloadingpointrate',
            name='amount_per_point',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
