# Generated by Django 5.2.9 on 2026-01-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0053_contractreferencedate_contracttemplate_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractreferencedate',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
