# Generated by Django 5.2.9 on 2026-01-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0054_contractreferencedate_is_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractReferenceDateTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ro', 'Romanian'), ('ru', 'Russian')], db_index=True, max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('reference_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_date_translations', to='att.contractreferencedate')),
            ],
            options={
                'verbose_name': 'Contract reference date translation',
                'verbose_name_plural': 'Contract reference date translations',
                'unique_together': {('reference_date', 'language')},
            },
        ),
    ]
