# Generated by Django 5.2.9 on 2026-01-14 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_usercompensationsettings'),
        ('att', '0055_contractreferencedatetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractreferencedate',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contract_references', to='app.company'),
        ),
    ]
