# Generated by Django 5.2.9 on 2026-01-14 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0056_alter_contractreferencedate_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contract_reference_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reference_date_contacts', to='att.contractreferencedate'),
        ),
    ]
