# Generated by Django 5.2.9 on 2026-01-14 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0057_contact_contract_reference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='reference_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reference_date_contracts', to='att.contractreferencedate'),
        ),
    ]
