# Generated by Django 5.2.9 on 2026-01-15 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0058_alter_contract_reference_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
