# Generated by Django 5.2.9 on 2026-01-17 12:10

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_unavailabilityreason'),
        ('att', '0061_contract_date_contract_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_driver_unavailabilities', to='app.company')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_unavailabilities', to=settings.AUTH_USER_MODEL)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reason_driver_unavailabilities', to='app.unavailabilityreason')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['driver', 'start_date', 'end_date'], name='att_driveru_driver__cd6524_idx')],
            },
        ),
        migrations.CreateModel(
            name='VehicleUnavailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_unavailabilities', to='app.company')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reason_vehicle_unavailabilities', to='app.unavailabilityreason')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_unavailabilities', to='att.vehicle')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['vehicle', 'start_date', 'end_date'], name='att_vehicle_vehicle_0b38d7_idx')],
            },
        ),
    ]
