# Generated by Django 5.2.9 on 2026-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0062_driverunavailability_vehicleunavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='normalized_reg_number',
            field=models.CharField(default='AAA-021', max_length=50),
            preserve_default=False,
        ),
    ]
