# Generated by Django 5.2.9 on 2026-01-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0063_vehicle_normalized_reg_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='adblue_tank_volume',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
