# Generated by Django 5.2.9 on 2026-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0065_alter_vehicle_height_alter_vehicle_length_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='weight_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
