# Generated by Django 5.2.10 on 2026-02-04 04:59

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0066_alter_vehicle_weight_capacity'),
        ('ayy', '0063_remove_documenttype_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('date_issued', models.DateField()),
                ('date_expiry', models.DateField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=abb.utils.image_upload_path)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_type_vehicle_documents', to='ayy.documenttype')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_documents', to='att.vehicle')),
            ],
            options={
                'ordering': ['-date_expiry'],
            },
        ),
    ]
