# Generated by Django 5.2.10 on 2026-02-04 11:38

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_companysettings_adblue_tank_volume_l_and_more'),
        ('att', '0067_vehicledocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ContactStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('is_blocking', models.BooleanField(default=False, help_text='If true, contact cannot be used in operations')),
                ('severity', models.PositiveSmallIntegerField(default=0, help_text='Higher = worse (used for sorting & UI color)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_contact_statuses', to='app.company')),
            ],
            options={
                'verbose_name': 'Contact Status',
                'verbose_name_plural': 'Contact Statuses',
                'ordering': ['severity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_contacts', to='att.contactstatus'),
        ),
        migrations.CreateModel(
            name='ContactStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_by_status_histories', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='att.contact')),
                ('new_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_status_histories', to='att.contactstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_status_histories', to='att.contactstatus')),
            ],
            options={
                'verbose_name': 'Contact Status History',
                'verbose_name_plural': 'Contact Status History',
                'ordering': ['-changed_at'],
            },
        ),
    ]
