# Generated by Django 5.2.10 on 2026-02-05 05:07

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('att', '0068_contact_status_updated_at_contactstatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledocument',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_vehicle_documents', to='app.company'),
        ),
        migrations.AddField(
            model_name='vehicledocument',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36),
        ),
    ]
