# Generated by Django 5.2.10 on 2026-02-05 05:08

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0069_vehicledocument_company_vehicledocument_uf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
    ]
