# Generated by Django 5.2.10 on 2026-02-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0070_alter_vehicledocument_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contract_reference_date',
        ),
    ]
