# Generated by Django 5.2.10 on 2026-02-14 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0071_remove_contact_contract_reference_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractreferencedate',
            name='usage',
            field=models.CharField(choices=[('contract', 'Contract'), ('invoice', 'Invoice'), ('both', 'Both')], db_index=True, default='both', max_length=10),
        ),
    ]
