# Generated by Django 5.2.10 on 2026-02-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0072_contractreferencedate_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contract_reference_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_reference_date_contacts', to='att.contractreferencedate'),
        ),
        migrations.AddField(
            model_name='contact',
            name='invoice_reference_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_reference_date_contacts', to='att.contractreferencedate'),
        ),
    ]
