# Generated by Django 5.2.10 on 2026-02-14 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0073_contact_contract_reference_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='invoice_reference_date',
        ),
        migrations.AddField(
            model_name='contract',
            name='invoice_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_date_contracts', to='att.contractreferencedate'),
        ),
    ]
