# Generated by Django 5.2.9 on 2026-01-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_unavailabilityreason'),
        ('att', '0062_driverunavailability_vehicleunavailability'),
        ('azz', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supplierformat',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('company', 'supplier'), name='one_active_supplier_format_per_company'),
        ),
    ]
