# Generated by Django 5.2.9 on 2026-01-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0002_supplierformat_one_active_supplier_format_per_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierformat',
            name='column_mapping',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
