# Generated by Django 5.2.9 on 2026-01-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0003_alter_supplierformat_column_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrow',
            name='supplier_row_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
