# Generated by Django 5.2.9 on 2026-01-20 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0004_importrow_supplier_row_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='importbatch',
            name='sequence',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='year',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
