# Generated by Django 5.2.9 on 2026-01-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0005_importbatch_sequence_importbatch_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierformat',
            name='country',
            field=models.CharField(default='MD'),
        ),
        migrations.AddField(
            model_name='supplierformat',
            name='currency',
            field=models.CharField(default='MDL'),
        ),
    ]
