# Generated by Django 5.2.9 on 2026-01-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0006_supplierformat_country_supplierformat_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierformat',
            name='country',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supplierformat',
            name='currency',
            field=models.CharField(blank=True, null=True),
        ),
    ]
