# Generated by Django 5.2.9 on 2026-01-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azz', '0007_alter_supplierformat_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierformat',
            name='country',
            field=models.CharField(default='MD'),
        ),
        migrations.AlterField(
            model_name='supplierformat',
            name='currency',
            field=models.CharField(default='MDL'),
        ),
    ]
