# Generated by Django 5.2.9 on 2026-01-22 13:04

import abb.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_companysettings'),
        ('att', '0066_alter_vehicle_weight_capacity'),
        ('azz', '0008_alter_supplierformat_country_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelTank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('adblue', 'AdBlue')], max_length=10)),
                ('capacity_l', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_fuel_tanks', to='app.company')),
            ],
            options={
                'unique_together': {('company', 'fuel_type')},
            },
        ),
        migrations.CreateModel(
            name='TankRefill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('date', models.DateTimeField()),
                ('quantity_l', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('actual_quantity_l', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_l', models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comments', models.TextField(blank=True, max_length=100)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_tank_refills', to='att.person')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supplier_tank_refills', to='att.contact')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_refills', to='azz.fueltank')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tank_refills', to='att.vehicleunit')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TruckFueling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('quantity_l', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fueled_at', models.DateTimeField()),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_truck_fuelings', to=settings.AUTH_USER_MODEL)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tank_truck_fuelings', to='azz.fueltank')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_truck_fuelings', to='att.vehicle')),
            ],
            options={
                'ordering': ['-fueled_at'],
            },
        ),
    ]
