# Generated by Django 5.2.9 on 2026-01-23 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0066_alter_vehicle_weight_capacity'),
        ('azz', '0009_fueltank_tankrefill_truckfueling'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankrefill',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tank_refills', to='att.vehicle'),
        ),
        migrations.AddIndex(
            model_name='tankrefill',
            index=models.Index(fields=['tank', '-date'], name='azz_tankref_tank_id_1e0c83_idx'),
        ),
        migrations.AddIndex(
            model_name='truckfueling',
            index=models.Index(fields=['tank', '-fueled_at'], name='azz_truckfu_tank_id_26eed3_idx'),
        ),
    ]
