# Generated by Django 5.2.9 on 2026-01-23 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayy', '0060_alter_itemforitemcost_options'),
        ('azz', '0010_alter_tankrefill_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckfueling',
            name='item_cost',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fueling_event', to='ayy.itemcost'),
        ),
    ]
