# Generated by Django 5.2.9 on 2025-12-05 14:17

import abb.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0001_initial'),
        ('app', '0002_userpersonalapitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('basic', 'basic'), ('pro', 'pro'), ('premium', 'premium')], default='basic', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('logo', models.CharField(blank=True, max_length=36, null=True)),
                ('stamp', models.CharField(blank=True, max_length=36, null=True)),
                ('company_name', models.CharField(blank=True, max_length=150, null=True)),
                ('fiscal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('vat_code', models.CharField(blank=True, max_length=20, null=True)),
                ('reg_com', models.CharField(blank=True, max_length=20, null=True)),
                ('subscribed_capital', models.CharField(blank=True, max_length=30, null=True)),
                ('zip_code_legal', models.CharField(blank=True, max_length=20, null=True)),
                ('city_legal', models.CharField(blank=True, max_length=50, null=True)),
                ('address_legal', models.CharField(blank=True, max_length=120, null=True)),
                ('county_legal', models.CharField(blank=True, max_length=10, null=True)),
                ('sect_legal', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code_post', models.CharField(blank=True, max_length=20, null=True)),
                ('city_post', models.CharField(blank=True, max_length=50, null=True)),
                ('address_post', models.CharField(blank=True, max_length=120, null=True)),
                ('county_post', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('messanger', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.CharField(blank=True, max_length=500, null=True)),
                ('is_vat_payer', models.BooleanField(default=False)),
                ('is_vat_on_receipt', models.BooleanField(default=False)),
                ('e_factura', models.BooleanField(default=False)),
                ('country_code_legal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycountry1', to='abb.country')),
                ('country_code_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companycountry2', to='abb.country')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_start', models.DateTimeField(blank=True, null=True)),
                ('date_exp', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('notifications', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), default=abb.utils.get_default_notification_status_3, size=3)),
                ('internal_use_only', models.TextField(blank=True, max_length=1000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_subscriptions', to='app.company')),
                ('plan', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.membership')),
            ],
            options={
                'ordering': ['date_exp'],
            },
        ),
    ]
