# Generated by Django 5.2.9 on 2025-12-07 11:03

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_user_date_of_birth_team_userpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_registered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_termination',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='DocumentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('series', models.CharField(max_length=20)),
                ('number_from', models.PositiveIntegerField()),
                ('number_to', models.PositiveIntegerField()),
                ('is_fiscal_invoice', models.BooleanField(default=False)),
                ('is_route_sheet', models.BooleanField(default=False)),
                ('is_cmr', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_document_series', to='app.company')),
            ],
            options={
                'verbose_name': 'Document Series',
                'verbose_name_plural': 'Document Series',
                'constraints': [models.UniqueConstraint(fields=('company', 'series', 'number_from', 'number_to'), name='unique_constraint Documents company-series-number_from-number_to')],
            },
        ),
    ]
