# Generated by Django 5.2.9 on 2025-12-07 12:06

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_date_registered_user_date_termination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('server', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('reply_to_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('default_from_name', models.CharField(max_length=30)),
                ('encrypted_password', models.BinaryField()),
                ('encryption_type', models.CharField(choices=[('ssl', 'SSL'), ('tls', 'TLS')], max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_smpt_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
