# Generated by Django 5.2.9 on 2025-12-12 14:34

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
        ('app', '0006_smtpsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('name_warehouse', models.CharField(max_length=255)),
                ('address_warehouse', models.TextField(blank=True, null=True)),
                ('city_warehouse', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code_warehouse', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_warehouses', to='app.company')),
                ('country_warehouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abb.country')),
            ],
        ),
    ]
