# Generated by Django 5.2.9 on 2025-12-13 06:07

import abb.utils
import abb.validators
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_warehouse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('theme', models.CharField(default='light', max_length=20)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('simplified_load', models.BooleanField(default=False)),
                ('default_document_tab', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), default=abb.utils.get_default_empty_strings_20, size=20, validators=[abb.validators.validate_columns_arrayfield_length_exactly_20])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
