# Generated by Django 5.2.9 on 2025-12-17 10:37

import abb.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='base_doc_lang',
            field=models.CharField(blank=True, choices=[('ro', 'Romanian'), ('en', 'English'), ('ru', 'Russian'), ('rr', 'Romanian/Russian')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ctr_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='exp_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='inv_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='load_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='myitems_all',
            field=models.CharField(blank=True, default='all', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='order_by',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), default=abb.utils.get_order_by_default, size=7),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='quote_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='rows_per_page',
            field=models.PositiveSmallIntegerField(blank=True, default=20, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='tor_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='trip_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=20, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
    ]
