# Generated by Django 5.2.9 on 2025-12-19 14:55

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_usersettings_base_doc_lang_usersettings_ctr_columns_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.SmallIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_categories', to='app.company')),
            ],
            options={
                'verbose_name': 'Category General',
                'verbose_name_plural': 'Categories General',
            },
        ),
    ]
