# Generated by Django 5.2.9 on 2025-12-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_typegeneral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygeneral',
            name='serial_number',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='typegeneral',
            name='serial_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
