# Generated by Django 5.2.9 on 2025-12-20 04:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_categorygeneral_serial_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorygeneral',
            old_name='name',
            new_name='label',
        ),
        migrations.RenameField(
            model_name='typegeneral',
            old_name='name',
            new_name='label',
        ),
        migrations.AddField(
            model_name='categorygeneral',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typegeneral',
            name='code',
            field=models.CharField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
