# Generated by Django 5.2.9 on 2025-12-20 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_name_categorygeneral_label_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygeneral',
            options={'ordering': ['serial_number'], 'verbose_name': 'Category General', 'verbose_name_plural': 'Categories General'},
        ),
        migrations.AlterModelOptions(
            name='typegeneral',
            options={'ordering': ['serial_number'], 'verbose_name': 'Type General', 'verbose_name_plural': 'Type General'},
        ),
    ]
