# Generated by Django 5.2.9 on 2025-12-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_categorygeneral_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='rows_per_page',
            field=models.PositiveSmallIntegerField(blank=True, default=15, null=True),
        ),
    ]
