# Generated by Django 5.2.9 on 2025-12-20 11:16

import abb.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_usersettings_rows_per_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ctr_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='exp_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='inv_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='load_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='quote_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='tor_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='trip_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=25, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
    ]
