# Generated by Django 5.2.9 on 2025-12-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_usersettings_ctr_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
