# Generated by Django 5.2.9 on 2025-12-31 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_vat_on_receipt',
        ),
    ]
