# Generated by Django 5.2.9 on 2026-01-02 16:51

import abb.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_remove_company_is_vat_on_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='ctr_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='exp_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='inv_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='load_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='quote_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='tor_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='trip_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
    ]
