# Generated by Django 5.2.9 on 2026-01-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_usersettings_ctr_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorygeneral',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='typegeneral',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
