# Generated by Django 5.2.9 on 2026-01-03 12:04

import abb.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_categorygeneral_is_system_typegeneral_is_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='trip_loads_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
    ]
