# Generated by Django 5.2.9 on 2026-01-05 14:47

import abb.utils
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_usersettings_load_due_columns'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='load_2_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='load_3_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='load_4_columns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=30, validators=[abb.utils.validate_columns_arrayfield_length_min_5]),
        ),
    ]
