# Generated by Django 5.2.9 on 2026-01-09 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
        ('app', '0025_usersettings_load_2_columns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='currency_default',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_default_user_settings', to='abb.currency'),
        ),
    ]
