# Generated by Django 5.2.9 on 2026-01-13 10:10

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usersettings_currency_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompensationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('has_per_km_income', models.BooleanField(default=False)),
                ('paid_by_loading_points', models.BooleanField(default=False)),
                ('paid_by_unloading_points', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compensation_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
