# Generated by Django 5.2.9 on 2026-01-16 09:43

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_usercompensationsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.SmallIntegerField(unique=True)),
                ('code', models.CharField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_types_cost', to='app.company')),
            ],
            options={
                'verbose_name': 'Type Cost',
                'verbose_name_plural': 'Types Cost',
                'ordering': ['serial_number'],
            },
        ),
    ]
