# Generated by Django 5.2.9 on 2026-01-17 12:10

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_typecost'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnavailabilityReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.SmallIntegerField(unique=True)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('for_vehicle', models.BooleanField(default=True)),
                ('for_driver', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_unavailability_reasons', to='app.company')),
            ],
        ),
    ]
