# Generated by Django 5.2.9 on 2026-01-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0009_alter_country_label_alter_country_value'),
        ('app', '0030_companysettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysettings',
            name='adblue_tank_volume_l',
        ),
        migrations.RemoveField(
            model_name='companysettings',
            name='diesel_tank_volume_l',
        ),
        migrations.AddField(
            model_name='companysettings',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_company_settings', to='abb.currency'),
        ),
    ]
