# Generated by Django 5.2.10 on 2026-02-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
