# Generated by Django 5.2.10 on 2026-02-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0010_alter_statustype_options'),
        ('app', '0033_remove_user_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Warehouse',
            new_name='LoadWarehouse',
        ),
    ]
