# Generated by Django 5.2.10 on 2026-02-24 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_warehouse_loadwarehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadwarehouse',
            name='address_warehouse',
            field=models.CharField(blank=True, null=True),
        ),
    ]
