# Generated by Django 5.2.10 on 2026-03-07 07:30

import abb.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lync_key_sequence',
            field=abb.security.fields.EncryptedJSONField(blank=True, null=True),
        ),
    ]
