# Generated by Django 5.2.10 on 2026-03-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_user_lync_key_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lync_key_sequence_hash',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
