# Generated by Django 5.2.10 on 2026-03-08 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_user_lync_key_sequence_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lync_key_sequence',
        ),
    ]
