# Generated by Django 5.2.10 on 2026-03-18 11:17

import app.validations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='broker_invoice_start_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[app.validations.validate_invoice_start_number]),
        ),
    ]
