# Generated by Django 5.2.10 on 2026-03-07 06:32

import abb.security.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('axx', '0050_loadmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSecret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', abb.security.fields.EncryptedJSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_load_secrets', to='app.company')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_load_secrets', to=settings.AUTH_USER_MODEL)),
                ('load', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='load_secrets', to='axx.load')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_load_secrets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['company'], name='lync_loadse_company_0a042a_idx')],
            },
        ),
    ]
