# Generated by Django 5.2.9 on 2025-12-07 07:34

import abb.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abb', '0002_bodytype_exchangerate_incoterm_modetype_statustype'),
        ('app', '0004_user_date_of_birth_team_userpermission'),
        ('att', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('rn', models.CharField(blank=True, max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('load_size', models.CharField(blank=True, choices=[('ltl', 'LTL'), ('ftl', 'FTL'), ('xpr', 'XPR')], max_length=20, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('incl_loads_costs', models.BooleanField(default=False)),
                ('doc_lang', models.CharField(blank=True, choices=[('ro', 'Romanian'), ('en', 'English'), ('ru', 'Russian'), ('rr', 'Romanian/Russian')], default='en', max_length=2, null=True)),
                ('trip_number', models.CharField(blank=True, max_length=20, null=True)),
                ('km_departure', models.CharField(blank=True, max_length=20, null=True)),
                ('km_arrival', models.CharField(blank=True, max_length=20, null=True)),
                ('date_trip', models.DateTimeField(blank=True, null=True)),
                ('date_departure', models.DateTimeField(blank=True, null=True)),
                ('date_arrival', models.DateTimeField(blank=True, null=True)),
                ('trip_details', models.CharField(blank=True, max_length=100, null=True)),
                ('l_departure', models.CharField(blank=True, max_length=20, null=True)),
                ('l_arrival', models.CharField(blank=True, max_length=20, null=True)),
                ('trip_add_info', models.CharField(blank=True, max_length=100, null=True)),
                ('load_order', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=36, null=True), blank=True, null=True, size=None), blank=True, null=True, size=None)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_trips', to=settings.AUTH_USER_MODEL)),
                ('bt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodytype_trips', to='abb.bodytype')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='carrier_trips', to='att.contact')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_trips', to='app.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_trips', to='abb.currency')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='att.person')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modetype_trips', to='abb.modetype')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_trips', to='att.person')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statustype_trips', to='abb.statustype')),
                ('vehicle_tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tractor_trips', to='att.vehicleunit')),
                ('vehicle_trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trailer_trips', to='att.vehicleunit')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('sn', models.CharField(blank=True, max_length=12, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_order', models.DateTimeField(blank=True, null=True)),
                ('date_due', models.DateTimeField(blank=True, null=True)),
                ('date_published', models.DateTimeField(blank=True, null=True)),
                ('load_size', models.CharField(blank=True, choices=[('ltl', 'LTL'), ('ftl', 'FTL'), ('xpr', 'XPR')], max_length=20, null=True)),
                ('customer_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('customer_notes', models.CharField(blank=True, max_length=200, null=True)),
                ('load_add_ons', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), blank=True, null=True, size=3)),
                ('doc_lang', models.CharField(blank=True, choices=[('ro', 'Romanian'), ('en', 'English'), ('ru', 'Russian'), ('rr', 'Romanian/Russian')], default='ro', max_length=2, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('hb', models.CharField(blank=True, max_length=30, null=True)),
                ('mb', models.CharField(blank=True, max_length=30, null=True)),
                ('booking_number', models.CharField(blank=True, max_length=30, null=True)),
                ('comment1', models.CharField(blank=True, max_length=200, null=True)),
                ('load_address', models.CharField(blank=True, max_length=100, null=True)),
                ('unload_address', models.CharField(blank=True, max_length=100, null=True)),
                ('load_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('assigned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_loads', to=settings.AUTH_USER_MODEL)),
                ('bill_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='bill_to_loads', to='att.contact')),
                ('bt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodytype_loads', to='abb.bodytype')),
                ('carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='carrier_loads', to='att.contact')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_loads', to='app.company')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_loads', to='abb.currency')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_loads', to='att.person')),
                ('incoterm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoterm_loads', to='abb.incoterm')),
                ('mode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modetype_loads', to='abb.modetype')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_term_loads', to='att.paymentterm')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_loads', to='att.person')),
                ('person_carrier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_carrier_loads', to='att.person')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statustype_loads', to='abb.statustype')),
                ('vehicle_tractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tractor_loads', to='att.vehicleunit')),
                ('vehicle_trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trailer_loads', to='att.vehicleunit')),
                ('trip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_loads', to='axx.trip')),
            ],
            options={
                'verbose_name': 'Load',
                'verbose_name_plural': 'Loads',
            },
        ),
    ]
