# Generated by Django 5.2.9 on 2025-12-12 14:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='load_stages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=3),
        ),
    ]
