# Generated by Django 5.2.9 on 2025-12-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0003_ctr_series_inv_tor_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_customs_cleared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='is_invoiced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='is_loaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='is_unloaded',
            field=models.BooleanField(default=False),
        ),
    ]
