# Generated by Django 5.2.9 on 2025-12-20 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0004_load_is_customs_cleared_load_is_invoiced_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='is_customs_cleared',
            new_name='is_cleared',
        ),
    ]
