# Generated by Django 5.2.9 on 2025-12-20 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0005_rename_is_customs_cleared_load_is_cleared'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trip_links', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_links', to='axx.trip')),
            ],
            options={
                'verbose_name': 'Trip driver',
                'verbose_name_plural': 'Trip drivers',
                'unique_together': {('trip', 'driver')},
            },
        ),
        migrations.AddField(
            model_name='trip',
            name='drivers',
            field=models.ManyToManyField(blank=True, related_name='drivers_trip', through='axx.TripDriver', to=settings.AUTH_USER_MODEL),
        ),
    ]
