# Generated by Django 5.2.9 on 2025-12-21 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0006_tripdriver_trip_drivers'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='km_entry',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='km_exit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
