# Generated by Django 5.2.9 on 2025-12-21 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0012_person_contact_alter_person_site'),
        ('axx', '0007_trip_km_entry_trip_km_exit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='vehicle_tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tractor_trips', to='att.vehiclecompany'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='vehicle_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trailer_trips', to='att.vehiclecompany'),
        ),
    ]
