# Generated by Django 5.2.9 on 2025-12-21 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0009_alter_trip_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='driver',
        ),
    ]
