# Generated by Django 5.2.9 on 2025-12-28 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0010_remove_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='load_type',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('external', 'External')], max_length=20, null=True),
        ),
    ]
