# Generated by Django 5.2.9 on 2025-12-28 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_userprofile'),
        ('axx', '0011_load_load_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_loads', to='app.categorygeneral'),
        ),
    ]
