# Generated by Django 5.2.9 on 2025-12-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0012_load_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='dgg_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='ins_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='tmc_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
