# Generated by Django 5.2.9 on 2025-12-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0013_load_dgg_details_load_ins_details_load_tmc_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('external', 'External')], max_length=20, null=True),
        ),
    ]
