# Generated by Django 5.2.9 on 2025-12-30 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0029_alter_bankaccount_bank_name'),
        ('axx', '0014_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_trips', to='att.person'),
        ),
    ]
