# Generated by Django 5.2.9 on 2025-12-31 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0033_remove_vehiclecompany_brand_and_more'),
        ('axx', '0015_trip_driver'),
    ]

    operations = [

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='trip',
                    name='rs_number',
                    field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT,
                                               related_name='number_route_sheet_number', to='att.routesheetnumber'),
                ), ]),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='trip',
                    name='vehicle_tractor',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='vehicle_tractor_trips', to='att.vehicle'),
                ), ]),

        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AlterField(
                    model_name='trip',
                    name='vehicle_trailer',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                            related_name='vehicle_trailer_trips', to='att.vehicle'),
                ), ]),
    ]
