# Generated by Django 5.2.9 on 2025-12-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0040_alter_vehicle_options'),
        ('axx', '0016_trip_rs_number_alter_trip_vehicle_tractor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='vehicle_tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tractor_loads', to='att.vehicle'),
        ),
    ]
