# Generated by Django 5.2.9 on 2025-12-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0040_alter_vehicle_options'),
        ('axx', '0017_alter_load_vehicle_tractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='vehicle_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trailer_loads', to='att.vehicle'),
        ),
        migrations.AlterField(
            model_name='tor',
            name='vehicle_tractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_tractor_tors', to='att.vehicle'),
        ),
        migrations.AlterField(
            model_name='tor',
            name='vehicle_trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicle_trailer_tors', to='att.vehicle'),
        ),
    ]
