# Generated by Django 5.2.9 on 2026-01-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0018_alter_load_vehicle_trailer_alter_tor_vehicle_tractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='date_cleared',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='date_loaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='date_unloaded',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
