# Generated by Django 5.2.9 on 2026-01-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0019_load_date_cleared_load_date_loaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
