# Generated by Django 5.2.9 on 2026-01-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0020_load_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='date_published',
        ),
    ]
