# Generated by Django 5.2.9 on 2026-01-04 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0021_remove_load_date_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='date_invoiced',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
