# Generated by Django 5.2.9 on 2026-01-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0022_load_date_invoiced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='load_type',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('external', 'External'), ('local', 'Local')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_type',
            field=models.CharField(blank=True, choices=[('own', 'Own'), ('external', 'External'), ('local', 'Local')], max_length=20, null=True),
        ),
    ]
