# Generated by Django 5.2.9 on 2026-01-04 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0023_alter_load_load_type_alter_trip_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='date_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
