# Generated by Django 5.2.9 on 2026-01-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0024_load_date_signed_load_is_paid_load_is_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='freight_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
