# Generated by Django 5.2.9 on 2026-01-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0025_load_freight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
