# Generated by Django 5.2.9 on 2026-01-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0026_trip_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='is_sent_shipper_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='load',
            name='shipper_email_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
