# Generated by Django 5.2.9 on 2026-01-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0027_load_is_sent_shipper_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='load',
            old_name='shipper_email_sent_at',
            new_name='date_shipper_email_sent',
        ),
    ]
