# Generated by Django 5.2.9 on 2026-01-10 04:49

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0028_rename_shipper_email_sent_at_load_date_shipper_email_sent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='date_shipper_email_sent',
        ),
        migrations.RemoveField(
            model_name='load',
            name='is_sent_shipper_email',
        ),
        migrations.CreateModel(
            name='LoadEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('event_type', models.CharField(choices=[('SHIPPER_EMAIL_SENT', 'Shipper email sent'), ('SHIPPER_CONFIRMED', 'Shipper confirmed'), ('DOCS_SENT_CNEE', 'Docs sent to consignee broker')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_events', to='axx.load')),
            ],
            options={
                'unique_together': {('load', 'event_type')},
            },
        ),
    ]
