# Generated by Django 5.2.9 on 2026-01-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0029_remove_load_date_shipper_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadevent',
            name='event_type',
            field=models.CharField(choices=[('SHIPPER_EMAIL_SENT', 'Shipper email sent'), ('SHIPPER_CONFIRMED', 'Shipper confirmed'), ('DOCS_SENT_CNEE_BROKER', 'Docs sent to consignee broker')], max_length=50),
        ),
    ]
