# Generated by Django 5.2.10 on 2026-01-27 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_remove_companysettings_adblue_tank_volume_l_and_more'),
        ('axx', '0031_tripadvancepaymentstatus_tripadvancepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripadvancepaymentstatus',
            name='description',
        ),
        migrations.AddField(
            model_name='tripadvancepaymentstatus',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tripadvancepaymentstatus',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_trip_advance_payment_statuses', to='app.company'),
        ),
    ]
