# Generated by Django 5.2.10 on 2026-01-28 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0032_remove_tripadvancepaymentstatus_description_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loadevent',
            unique_together=set(),
        ),
    ]
