# Generated by Django 5.2.10 on 2026-02-06 08:29

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('axx', '0033_alter_loadevent_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(blank=True, max_length=32, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('amount_mdl', models.DecimalField(decimal_places=4, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('rate_date', models.DateField()),
                ('original_amount', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount_overridden', models.BooleanField(default=False)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=16)),
                ('invoice_type', models.CharField(choices=[('standard', 'Standard'), ('credit', 'Credit note'), ('debit', 'Debit note')], default='standard', max_length=16)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_load_invs', to='app.company')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_by_load_invs', to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_load_invs', to='axx.load')),
            ],
            options={
                'indexes': [models.Index(fields=['issued_date'], name='axx_loadinv_issued__a9f40b_idx'), models.Index(fields=['company'], name='axx_loadinv_company_be63db_idx'), models.Index(fields=['status'], name='axx_loadinv_status_731080_idx')],
                'constraints': [models.UniqueConstraint(fields=('company', 'invoice_number'), name='uniq_invoice_number_per_company')],
            },
        ),
    ]
