# Generated by Django 5.2.10 on 2026-02-07 07:52

import abb.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('axx', '0034_loadinv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoadDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('doc_type', models.CharField(choices=[('customer_order', 'Customer Order'), ('proforma_invoice', 'Proforma Invoice'), ('invoice', 'Invoice'), ('act', 'Act of Execution of Services')], max_length=32)),
                ('file', models.FileField(upload_to=abb.utils.image_upload_path)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_load_documents', to='app.company')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_documents', to='axx.load')),
            ],
            options={
                'unique_together': {('load', 'doc_type', 'is_active')},
            },
        ),
    ]
