# Generated by Django 5.2.10 on 2026-02-07 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_userprofile_avatar'),
        ('axx', '0035_loaddocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='loaddocument',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='loaddocument',
            name='doc_type',
            field=models.CharField(choices=[('order', 'Customer Order'), ('proforma', 'Proforma Invoice'), ('invoice', 'Invoice'), ('act', 'Act of Execution of Services')], max_length=32),
        ),
        migrations.AddConstraint(
            model_name='loaddocument',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('load', 'doc_type'), name='unique_active_document_per_type'),
        ),
    ]
