# Generated by Django 5.2.10 on 2026-02-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0037_loadinv_cancelled_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadinv',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
