# Generated by Django 5.2.10 on 2026-02-17 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('axx', '0038_loadinv_cancelled_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='payment_term',
        ),
        migrations.AddField(
            model_name='load',
            name='invoice_reference_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_reference_date_loads', to='att.contractreferencedate'),
        ),
        migrations.AddField(
            model_name='load',
            name='payment_reference_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reference_date_loads', to='att.contractreferencedate'),
        ),
    ]
