# Generated by Django 5.2.10 on 2026-02-17 10:09

import abb.utils
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_image'),
        ('axx', '0039_remove_load_payment_term_load_invoice_reference_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='driver_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('available', 'Available'), ('locked', 'Locked'), ('loaded', 'Loaded')], default='locked', max_length=20),
        ),
        migrations.AddField(
            model_name='trip',
            name='driver_load_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=36), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='LoadEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('type', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to=abb.utils.image_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_load_evidences', to='app.company')),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='load_evidences', to='axx.load')),
            ],
        ),
    ]
