# Generated by Django 5.2.10 on 2026-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0040_load_driver_status_trip_driver_load_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadevidence',
            name='type',
            field=models.CharField(choices=[('cargo', 'Cargo'), ('cmr', 'CMR'), ('damage', 'Damage'), ('seal', 'Seal'), ('other', 'Other')], default='cargo', max_length=20),
        ),
    ]
