# Generated by Django 5.2.10 on 2026-02-17 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0041_alter_loadevidence_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadevidence',
            name='company',
        ),
    ]
