# Generated by Django 5.2.10 on 2026-02-18 05:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_remove_user_image'),
        ('axx', '0042_remove_loadevidence_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loadinv',
            index=models.Index(fields=['invoice_type'], name='axx_loadinv_invoice_2122c1_idx'),
        ),
    ]
