# Generated by Django 5.2.10 on 2026-02-18 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0043_loadinv_axx_loadinv_invoice_2122c1_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='driver_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('locked', 'Locked'), ('arrived_pickup', 'Arrived at Pickup'), ('loading', 'Loading'), ('loaded', 'Loaded'), ('departed', 'Departed'), ('arrived_delivery', 'Arrived at Delivery'), ('unloading', 'Unloading'), ('completed', 'Completed')], default='locked', max_length=20),
        ),
    ]
