# Generated by Django 5.2.10 on 2026-02-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0044_alter_load_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_inspection_completed',
            field=models.BooleanField(default=False),
        ),
    ]
