# Generated by Django 5.2.10 on 2026-02-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0045_trip_departure_inspection_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_inspection_completed',
            field=models.BooleanField(default=False),
        ),
    ]
