# Generated by Django 5.2.10 on 2026-02-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0046_trip_arrival_inspection_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='stops_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
