# Generated by Django 5.2.10 on 2026-02-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0047_trip_stops_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='driver_status',
        ),
    ]
