# Generated by Django 5.2.10 on 2026-02-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_warehouse_loadwarehouse'),
        ('axx', '0048_remove_load_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='location_type',
            field=models.CharField(choices=[('trip', 'On Trip / Vehicle'), ('warehouse', 'In Warehouse'), ('delivered', 'Delivered')], default='trip', max_length=20),
        ),
        migrations.AddField(
            model_name='load',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_loads', to='app.loadwarehouse'),
        ),
    ]
