# Generated by Django 5.2.10 on 2026-03-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0050_loadmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='km_end_driver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='km_start_driver',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
