# Generated by Django 5.2.10 on 2026-03-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0051_trip_km_end_driver_trip_km_start_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='km_end_driver_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='km_start_driver_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
