# Generated by Django 5.2.10 on 2026-03-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0052_trip_km_end_driver_recorded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadmovement',
            name='role',
            field=models.CharField(blank=True, choices=[('loading', 'Loading side'), ('unloading', 'Unloading side')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loadmovement',
            name='status',
            field=models.CharField(blank=True, choices=[('expected_warehouse', 'Expected at warehouse'), ('arrived_warehouse', 'Arrived at warehouse'), ('left_warehouse', 'Left warehouse'), ('in_transit', 'In transit')], max_length=40, null=True),
        ),
    ]
