# Generated by Django 5.2.10 on 2026-03-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0002_jobline'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='job',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, db_index=True, default='new', max_length=30, null=True),
        ),
    ]
