# Generated by Django 5.2.10 on 2026-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0003_servicetype_vat_percent_alter_job_ref_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobline',
            options={},
        ),
        migrations.RenameField(
            model_name='jobline',
            old_name='unit_price',
            new_name='unit_price_net',
        ),
        migrations.RemoveField(
            model_name='jobline',
            name='description',
        ),
        migrations.AddField(
            model_name='jobline',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
