# Generated by Django 5.2.10 on 2026-03-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0004_alter_jobline_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='comments',
            field=models.CharField(blank=True, null=True),
        ),
    ]
