# Generated by Django 5.2.10 on 2026-03-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0005_job_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobline',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
