# Generated by Django 5.2.10 on 2026-03-10 10:31

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('broker', '0006_jobline_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceGroupItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='jobline',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='pointofservice',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='servicetype',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='jobline',
            name='parent_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_line_children', to='broker.jobline'),
        ),
        migrations.AddField(
            model_name='jobline',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='comments',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddIndex(
            model_name='customerserviceprice',
            index=models.Index(fields=['company', 'customer'], name='broker_cust_company_d7b900_idx'),
        ),
        migrations.AddIndex(
            model_name='customerserviceprice',
            index=models.Index(fields=['company', 'service_type'], name='broker_cust_company_dd6b9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='pointofservice',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_point_name_per_company'),
        ),
        migrations.AddConstraint(
            model_name='servicetype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='uniq_service_type_code_per_company'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_service_groups', to='app.company'),
        ),
        migrations.AddField(
            model_name='servicegroup',
            name='main_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_service_groups', to='broker.servicetype'),
        ),
        migrations.AddField(
            model_name='jobline',
            name='service_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_group_job_lines', to='broker.servicegroup'),
        ),
        migrations.AddIndex(
            model_name='jobline',
            index=models.Index(fields=['job', 'parent_line', 'position'], name='broker_jobl_job_id_9c5cc8_idx'),
        ),
        migrations.AddIndex(
            model_name='jobline',
            index=models.Index(fields=['service_group'], name='broker_jobl_service_219cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='jobline',
            index=models.Index(fields=['service_type'], name='broker_jobl_service_70f8aa_idx'),
        ),
        migrations.AddField(
            model_name='servicegroupitem',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_group_items', to='broker.servicegroup'),
        ),
        migrations.AddField(
            model_name='servicegroupitem',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='broker.servicetype'),
        ),
        migrations.AddConstraint(
            model_name='servicegroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_service_group_name'),
        ),
        migrations.AddConstraint(
            model_name='servicegroupitem',
            constraint=models.UniqueConstraint(fields=('group', 'service_type'), name='uniq_service_group_item'),
        ),
    ]
