# Generated by Django 5.2.10 on 2026-03-10 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0007_servicegroup_servicegroupitem_alter_jobline_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_quantity', models.PositiveIntegerField()),
                ('to_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='broker.servicetype')),
            ],
            options={
                'ordering': ['from_quantity'],
            },
        ),
    ]
