# Generated by Django 5.2.10 on 2026-03-10 11:28

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0008_servicetypetier'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetypetier',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
    ]
