# Generated by Django 5.2.10 on 2026-03-10 12:32

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('broker', '0009_servicetypetier_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerServiceTierPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_tier_prices', to='app.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_service_tier_prices', to='att.contact')),
                ('service_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_prices', to='broker.servicetypetier')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('customer', 'service_tier'), name='uniq_customer_service_tier_price')],
            },
        ),
    ]
