# Generated by Django 5.2.10 on 2026-03-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0011_customerserviceprice_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_add_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
