# Generated by Django 5.2.10 on 2026-03-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0012_job_job_add_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobline',
            name='other_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
