# Generated by Django 5.2.10 on 2026-03-11 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('broker', '0014_brokerbasesalary_brokercommission_brokersettlement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='brokercommission',
            name='type',
            field=models.CharField(choices=[('incl_vat', 'Including VAT'), ('excl_vat', 'Excluding VAT')], default='excl_vat', max_length=20),
        ),
        migrations.AddIndex(
            model_name='brokercommission',
            index=models.Index(fields=['company', 'user'], name='broker_brok_company_1332a1_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokercommission',
            constraint=models.UniqueConstraint(fields=('company', 'user', 'customer', 'service_type', 'valid_from'), name='unique_broker_commission_rule'),
        ),
    ]
