# Generated by Django 5.2.10 on 2026-03-11 13:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('broker', '0015_alter_brokercommission_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokersettlement',
            name='unique_broker_job_settlement',
        ),
        migrations.RemoveIndex(
            model_name='brokersettlement',
            name='broker_brok_company_3dbfa7_idx',
        ),
        migrations.RenameField(
            model_name='brokersettlement',
            old_name='income',
            new_name='base_salary',
        ),
        migrations.RemoveField(
            model_name='brokersettlement',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='brokersettlement',
            name='job',
        ),
        migrations.AddField(
            model_name='brokersettlement',
            name='commission_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokersettlement',
            name='period_end',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokersettlement',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brokersettlement',
            name='total_income',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brokersettlement',
            name='broker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='brokersettlement',
            name='settlement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='brokersettlement',
            constraint=models.UniqueConstraint(fields=('broker', 'period_start', 'period_end'), name='unique_broker_period_start_period_end_settlement'),
        ),
    ]
