# Generated by Django 5.2.10 on 2026-03-18 05:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('broker', '0016_remove_brokersettlement_unique_broker_job_settlement_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokercommission',
            name='unique_broker_commission_rule',
        ),
        migrations.AddConstraint(
            model_name='brokercommission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('customer__isnull', False), ('service_type__isnull', True)), models.Q(('customer__isnull', True), ('service_type__isnull', False)), models.Q(('customer__isnull', True), ('service_type__isnull', True)), _connector='OR'), name='broker_commission_only_one_scope'),
        ),
    ]
