# Generated by Django 5.2.10 on 2026-03-18 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0017_remove_brokercommission_unique_broker_commission_rule_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='brokercommission',
            name='broker_commission_only_one_scope',
        ),
    ]
