# Generated by Django 5.2.10 on 2026-03-18 10:04

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('broker', '0019_job_date_job_job_invoice_status_job_job_invoice_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50)),
                ('invoice_date', models.DateField()),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount_net', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_gross', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='broker_job_company_5a348b_idx',
        ),
        migrations.RemoveField(
            model_name='job',
            name='invoice_status',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_invoice_date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_invoice_issued_at',
        ),
        migrations.RemoveField(
            model_name='job',
            name='job_invoice_number',
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('created', 'Created')], db_index=True, default='created', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='brokerinvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_invoices', to='app.company'),
        ),
        migrations.AddField(
            model_name='brokerinvoice',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_broker_invoices', to='att.contact'),
        ),
        migrations.AddField(
            model_name='job',
            name='broker_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broker_invoice_jobs', to='broker.brokerinvoice'),
        ),
        migrations.AddField(
            model_name='brokerinvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_invoice_lines', to='broker.brokerinvoice'),
        ),
        migrations.AddField(
            model_name='brokerinvoiceline',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_invoice_lines', to='broker.job'),
        ),
    ]
