# Generated by Django 5.2.10 on 2026-03-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0020_brokerinvoice_brokerinvoiceline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('created', 'Created')], db_index=True, default='created', max_length=30, null=True),
        ),
    ]
