# Generated by Django 5.2.10 on 2026-03-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0021_alter_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='brokerinvoiceline',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
