# Generated by Django 5.2.10 on 2026-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0022_brokerinvoiceline_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brokerinvoiceline',
            options={'ordering': ['position']},
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('created', 'Created')], db_index=True, default='created', max_length=30),
        ),
    ]
