# Generated by Django 5.2.10 on 2026-03-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0023_alter_brokerinvoiceline_options_alter_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_job',
            field=models.DateField(blank=True, null=True),
        ),
    ]
