# Generated by Django 5.2.10 on 2026-03-19 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('broker', '0024_alter_job_date_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('created', 'Created'), ('pending', 'Pending'), ('finished', 'Finished')], db_index=True, default='created', max_length=30),
        ),
    ]
