# Generated by Django 5.2.10 on 2026-02-03 14:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclechecklist',
            name='inspection_type',
            field=models.CharField(choices=[('departure', 'Departure'), ('arrival', 'Arrival')], db_index=True, default='departure', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclechecklist',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclechecklist',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_checklists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vehiclechecklistanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclechecklistanswer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_checklist_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
