# Generated by Django 5.2.10 on 2026-02-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baa', '0002_vehiclechecklist_inspection_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclechecklistitem',
            name='applies_to_arrival',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiclechecklistitem',
            name='applies_to_departure',
            field=models.BooleanField(default=True),
        ),
    ]
