# Generated by Django 5.2.10 on 2026-02-19 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axx', '0046_trip_arrival_inspection_completed'),
        ('baa', '0003_vehiclechecklistitem_applies_to_arrival_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclechecklist',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trip_checklists', to='axx.trip'),
        ),
    ]
