# Generated by Django 5.2.10 on 2026-01-26 13:44

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0031_remove_companysettings_adblue_tank_volume_l_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('code', models.CharField(max_length=20)),
                ('label', models.CharField(max_length=30)),
                ('is_system', models.BooleanField(default=False)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_payment_methods', to='app.company')),
            ],
            options={
                'ordering': ['is_system', 'serial_number'],
            },
        ),
    ]
