# Generated by Django 5.2.9 on 2025-12-05 14:17

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('label', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=120, unique=True)),
                ('value_iso3', models.CharField(max_length=3)),
                ('value_numeric', models.CharField(max_length=3)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('currency_code', models.CharField(max_length=3, unique=True)),
                ('currency_name', models.CharField(blank=True, max_length=70, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=70, null=True)),
                ('currency_numeric', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
