# Generated by Django 5.2.9 on 2025-12-07 07:34

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('bt', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name': 'Body type',
                'verbose_name_plural': 'Body types',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('date', models.DateField()),
                ('metadata_nbr', models.JSONField(blank=True, null=True)),
                ('metadata_nbm', models.JSONField(blank=True, null=True)),
                ('metadata_nbu', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Exchange Rate',
                'verbose_name_plural': 'Exchange Rates',
            },
        ),
        migrations.CreateModel(
            name='Incoterm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('it', models.CharField(max_length=3)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Incoterm',
                'verbose_name_plural': 'Incoterms',
            },
        ),
        migrations.CreateModel(
            name='ModeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('mt', models.CharField(max_length=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Mode transport type',
                'verbose_name_plural': 'Mode transport types',
            },
        ),
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('serial_number', models.PositiveSmallIntegerField(unique=True)),
                ('order_number', models.PositiveSmallIntegerField(blank=True, null=True, unique=True)),
                ('st', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['serial_number'],
            },
        ),
    ]
