# Generated by Django 5.2.9 on 2025-12-07 12:06

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0002_bodytype_exchangerate_incoterm_modetype_statustype'),
    ]

    operations = [
        migrations.AddField(
            model_name='modetype',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='statustype',
            name='uf',
            field=models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
    ]
