# Generated by Django 5.2.9 on 2025-12-20 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0003_modetype_uf_alter_statustype_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='statustype',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='StatusTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(db_index=True, max_length=2)),
                ('label', models.CharField(max_length=255)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='abb.statustype')),
            ],
            options={
                'indexes': [models.Index(fields=['language'], name='abb_statust_languag_203a2c_idx')],
                'unique_together': {('status', 'language')},
            },
        ),
    ]
