# Generated by Django 5.2.9 on 2025-12-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0004_statustype_code_statustypetranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='modetype',
            name='code',
            field=models.CharField(default='first', max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modetype',
            name='label',
            field=models.CharField(default='codde', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
