# Generated by Django 5.2.9 on 2025-12-28 10:45

import abb.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0005_modetype_code_modetype_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodytype',
            name='bt',
        ),
        migrations.RemoveField(
            model_name='bodytype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modetype',
            name='description',
        ),
        migrations.RemoveField(
            model_name='modetype',
            name='mt',
        ),
        migrations.AddField(
            model_name='bodytype',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='bodytype',
            name='label',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='modetype',
            name='code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='modetype',
            name='label',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='modetype',
            name='uf',
            field=models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True),
        ),
    ]
