# Generated by Django 5.2.9 on 2025-12-28 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0006_remove_bodytype_bt_remove_bodytype_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bodytype',
            options={'ordering': ['serial_number'], 'verbose_name': 'Body type', 'verbose_name_plural': 'Body types'},
        ),
        migrations.AlterModelOptions(
            name='modetype',
            options={'ordering': ['serial_number'], 'verbose_name': 'Mode transport type', 'verbose_name_plural': 'Mode transport types'},
        ),
        migrations.RenameField(
            model_name='incoterm',
            old_name='it',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='incoterm',
            old_name='description',
            new_name='label',
        ),
    ]
