# Generated by Django 5.2.9 on 2025-12-28 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0007_alter_bodytype_options_alter_modetype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incoterm',
            options={'ordering': ['serial_number'], 'verbose_name': 'Incoterm', 'verbose_name_plural': 'Incoterms'},
        ),
    ]
