# Generated by Django 5.2.9 on 2026-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0008_alter_incoterm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='label',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='value',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
