# Generated by Django 5.2.10 on 2026-02-19 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abb', '0009_alter_country_label_alter_country_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statustype',
            options={'ordering': ['serial_number'], 'verbose_name': 'Status Type', 'verbose_name_plural': 'Status Types'},
        ),
    ]
