# Generated by Django 5.2.10 on 2026-03-04 05:13

import abb.utils
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WHInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_inbounds', to='app.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_wh_inbounds', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wh_inbounds', to='att.contact')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_by_wh_inbounds', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WHLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('code', models.CharField(max_length=40)),
                ('name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_locations', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='WHPortalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_portal_accounts', to='app.company')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_portal_accounts', to='att.contact')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='person_portal_accounts', to='att.person')),
            ],
        ),
        migrations.CreateModel(
            name='WHOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('reference', models.CharField(blank=True, max_length=80, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('shipped', 'Shipped'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('planned_pickup_at', models.DateTimeField(blank=True, null=True)),
                ('shipped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_outbounds', to='app.company')),
                ('contact_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_person_wh_outbounds', to='att.person')),
                ('created_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_user_wh_outbounds', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wh_outbounds', to='att.contact')),
                ('created_by_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crated_by_portal_wh_outbounds', to='logistic.whportalaccount')),
            ],
        ),
        migrations.CreateModel(
            name='WHProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('sku', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('uom', models.CharField(default='pcs', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_products', to='app.company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_wh_products', to='att.contact')),
            ],
        ),
        migrations.CreateModel(
            name='WHOutboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_lines', to='logistic.whoutbound')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_outbound_lines', to='logistic.whproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WHInboundLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('inbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_lines', to='logistic.whinbound')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_inbound_lines', to='logistic.whlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_inbound_lines', to='logistic.whproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WHStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_stocks', to='app.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_stock_rows', to='logistic.whlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_stock_rows', to='logistic.whproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WHStockLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('delta', models.DecimalField(decimal_places=3, max_digits=18)),
                ('source_type', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('adjustment', 'Adjustment')], max_length=20)),
                ('source_uf', models.CharField(db_index=True, max_length=36)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_portal_stock_ledgers', to='logistic.whportalaccount')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_user_stock_ledgers', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_stock_ledger', to='app.company')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='location_ledger_rows', to='logistic.whlocation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_ledger_rows', to='logistic.whproduct')),
            ],
        ),
        migrations.CreateModel(
            name='WHTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('storage_per_unit_per_day', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('inbound_per_line', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('outbound_per_order', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('outbound_per_line', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wms_tariffs', to='app.company')),
            ],
        ),
        migrations.CreateModel(
            name='WHContactTariffOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('storage_per_unit_per_day', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('inbound_per_line', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('outbound_per_order', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('outbound_per_line', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_wh_contact_tariff_overrides', to='app.company')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_wh_tariff_overrides', to='att.contact')),
            ],
            options={
                'indexes': [models.Index(fields=['company', 'contact'], name='logistic_wh_company_9c2126_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='whinbound',
            index=models.Index(fields=['company', 'owner', 'status'], name='logistic_wh_company_89208f_idx'),
        ),
        migrations.AddIndex(
            model_name='whinbound',
            index=models.Index(fields=['company', 'created_at'], name='logistic_wh_company_064b38_idx'),
        ),
        migrations.AddIndex(
            model_name='whlocation',
            index=models.Index(fields=['company', 'is_active'], name='logistic_wh_company_6fce84_idx'),
        ),
        migrations.AddConstraint(
            model_name='whlocation',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('code'), name='uniq_location_company_code_ci'),
        ),
        migrations.AddIndex(
            model_name='whportalaccount',
            index=models.Index(fields=['company', 'contact'], name='logistic_wh_company_65b77e_idx'),
        ),
        migrations.AddIndex(
            model_name='whportalaccount',
            index=models.Index(fields=['company', 'is_active'], name='logistic_wh_company_3b630e_idx'),
        ),
        migrations.AddConstraint(
            model_name='whportalaccount',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('email'), name='uniq_portal_company_email_ci'),
        ),
        migrations.AddIndex(
            model_name='whoutbound',
            index=models.Index(fields=['company', 'owner', 'status'], name='logistic_wh_company_97910d_idx'),
        ),
        migrations.AddIndex(
            model_name='whoutbound',
            index=models.Index(fields=['company', 'created_at'], name='logistic_wh_company_dcde84_idx'),
        ),
        migrations.AddConstraint(
            model_name='whoutbound',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('created_by_user__isnull', False), ('created_by_portal__isnull', True)), models.Q(('created_by_user__isnull', True), ('created_by_portal__isnull', False)), models.Q(('created_by_user__isnull', True), ('created_by_portal__isnull', True)), _connector='OR'), name='chk_outbound_creator_one_or_none'),
        ),
        migrations.AddIndex(
            model_name='whproduct',
            index=models.Index(fields=['company', 'owner'], name='logistic_wh_company_8fd1d7_idx'),
        ),
        migrations.AddIndex(
            model_name='whproduct',
            index=models.Index(fields=['company', 'sku'], name='logistic_wh_company_ee3828_idx'),
        ),
        migrations.AddConstraint(
            model_name='whproduct',
            constraint=models.UniqueConstraint(models.F('company'), models.F('owner'), django.db.models.functions.text.Lower('sku'), name='uniq_product_owner_sku_ci'),
        ),
        migrations.AddIndex(
            model_name='whoutboundline',
            index=models.Index(fields=['outbound'], name='logistic_wh_outboun_e0e392_idx'),
        ),
        migrations.AddIndex(
            model_name='whoutboundline',
            index=models.Index(fields=['product'], name='logistic_wh_product_af2913_idx'),
        ),
        migrations.AddConstraint(
            model_name='whoutboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_outboundline_qty_gt_0'),
        ),
        migrations.AddIndex(
            model_name='whinboundline',
            index=models.Index(fields=['inbound'], name='logistic_wh_inbound_6f42ca_idx'),
        ),
        migrations.AddIndex(
            model_name='whinboundline',
            index=models.Index(fields=['product'], name='logistic_wh_product_6d9dc5_idx'),
        ),
        migrations.AddConstraint(
            model_name='whinboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_inboundline_qty_gt_0'),
        ),
        migrations.AddIndex(
            model_name='whstock',
            index=models.Index(fields=['company', 'product'], name='logistic_wh_company_88a3e9_idx'),
        ),
        migrations.AddIndex(
            model_name='whstock',
            index=models.Index(fields=['company', 'location'], name='logistic_wh_company_d684dc_idx'),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.UniqueConstraint(models.F('product'), models.F('location'), name='uniq_stock_product_location'),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='chk_stock_non_negative'),
        ),
        migrations.AddIndex(
            model_name='whstockledger',
            index=models.Index(fields=['company', 'product', 'created_at'], name='logistic_wh_company_98f449_idx'),
        ),
        migrations.AddIndex(
            model_name='whstockledger',
            index=models.Index(fields=['company', 'source_type', 'source_uf'], name='logistic_wh_company_f454e4_idx'),
        ),
        migrations.AddConstraint(
            model_name='whstockledger',
            constraint=models.CheckConstraint(condition=models.Q(('delta', 0), _negated=True), name='chk_ledger_delta_nonzero'),
        ),
        migrations.AddIndex(
            model_name='whtariff',
            index=models.Index(fields=['company', 'is_active'], name='logistic_wh_company_bd1917_idx'),
        ),
    ]
