# Generated by Django 5.2.10 on 2026-03-05 09:44

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHBillingCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('charge_type', models.CharField(choices=[('storage', 'Storage'), ('inbound', 'Inbound'), ('outbound_order', 'Outbound Order'), ('outbound_line', 'Outbound Line')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('source_model', models.CharField(max_length=50)),
                ('source_uf', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WHBillingInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WHBillingInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('charge_type', models.CharField(choices=[('storage', 'Storage'), ('inbound', 'Inbound'), ('outbound_order', 'Outbound Order'), ('outbound_line', 'Outbound Line')], max_length=30)),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WHBillingPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WHPallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('pallet_code', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('shipped', 'Shipped'), ('closed', 'Closed')], default='active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WHPalletItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='WHPalletMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='whstock',
            name='uniq_stock_product_location',
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='storage_mode',
            field=models.CharField(blank=True, choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'M2'), ('volume', 'Volume')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_mode',
            field=models.CharField(choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'M2'), ('volume', 'Volume')], default='m2', max_length=20),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_per_m2_per_day',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_per_m3_per_day',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_per_pallet_per_day',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.UniqueConstraint(fields=('company', 'product', 'location'), name='uniq_stock_company_product_location'),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.contact'),
        ),
        migrations.AddField(
            model_name='whbillinginvoice',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='whbillinginvoice',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.contact'),
        ),
        migrations.AddField(
            model_name='whbillinginvoiceline',
            name='charges',
            field=models.ManyToManyField(blank=True, related_name='invoice_lines', to='logistic.whbillingcharge'),
        ),
        migrations.AddField(
            model_name='whbillinginvoiceline',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_wh_lines', to='logistic.whbillinginvoice'),
        ),
        migrations.AddField(
            model_name='whbillingperiod',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='whbillinginvoice',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.whbillingperiod'),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='billing_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.whbillingperiod'),
        ),
        migrations.AddField(
            model_name='whpallet',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.company'),
        ),
        migrations.AddField(
            model_name='whpallet',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.whlocation'),
        ),
        migrations.AddField(
            model_name='whpallet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='att.contact'),
        ),
        migrations.AddField(
            model_name='whpalletitem',
            name='pallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistic.whpallet'),
        ),
        migrations.AddField(
            model_name='whpalletitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistic.whproduct'),
        ),
        migrations.AddField(
            model_name='whpalletmove',
            name='from_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_location_pallet_moves', to='logistic.whlocation'),
        ),
        migrations.AddField(
            model_name='whpalletmove',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.whpallet'),
        ),
        migrations.AddField(
            model_name='whpalletmove',
            name='to_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_locations_pallet_moves', to='logistic.whlocation'),
        ),
        migrations.AddIndex(
            model_name='whbillinginvoiceline',
            index=models.Index(fields=['invoice', 'charge_type'], name='logistic_wh_invoice_9b48ce_idx'),
        ),
        migrations.AddIndex(
            model_name='whbillinginvoiceline',
            index=models.Index(fields=['invoice'], name='logistic_wh_invoice_a7b6ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='whbillingperiod',
            constraint=models.UniqueConstraint(fields=('company', 'start_date', 'end_date'), name='uniq_company_billing_period'),
        ),
        migrations.AddIndex(
            model_name='whbillingcharge',
            index=models.Index(fields=['company', 'billing_period'], name='logistic_wh_company_b571b8_idx'),
        ),
        migrations.AddIndex(
            model_name='whbillingcharge',
            index=models.Index(fields=['contact', 'billing_period'], name='logistic_wh_contact_4895c6_idx'),
        ),
        migrations.AddIndex(
            model_name='whbillingcharge',
            index=models.Index(fields=['company', 'source_model', 'source_uf'], name='logistic_wh_company_33b4e0_idx'),
        ),
        migrations.AddIndex(
            model_name='whpallet',
            index=models.Index(fields=['company'], name='logistic_wh_company_70bd65_idx'),
        ),
        migrations.AddIndex(
            model_name='whpallet',
            index=models.Index(fields=['owner'], name='logistic_wh_owner_i_6240bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='whpalletitem',
            constraint=models.UniqueConstraint(fields=('pallet', 'product'), name='uniq_pallet_product'),
        ),
    ]
