# Generated by Django 5.2.10 on 2026-03-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0002_whbillingcharge_whbillinginvoice_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whstock',
            name='uniq_stock_company_product_location',
        ),
        migrations.AddField(
            model_name='whstock',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_wh_stocks', to='att.contact'),
        ),
        migrations.AlterField(
            model_name='whpalletmove',
            name='pallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pallet_moves', to='logistic.whpallet'),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.UniqueConstraint(fields=('company', 'owner', 'product', 'location'), name='uniq_stock_company_owner_product_location'),
        ),
    ]
