# Generated by Django 5.2.10 on 2026-03-05 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0003_remove_whstock_uniq_stock_company_product_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whpallet',
            name='ended_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='whpallet',
            name='status_changed_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddIndex(
            model_name='whbillinginvoice',
            index=models.Index(fields=['company', 'period'], name='logistic_wh_company_c76a27_idx'),
        ),
        migrations.AddIndex(
            model_name='whbillinginvoice',
            index=models.Index(fields=['contact', 'period'], name='logistic_wh_contact_be3c6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='whbillinginvoice',
            constraint=models.UniqueConstraint(fields=('company', 'contact', 'period'), name='uniq_invoice_company_contact_period'),
        ),
        migrations.AddConstraint(
            model_name='whbillinginvoiceline',
            constraint=models.UniqueConstraint(fields=('invoice', 'charge_type'), name='uniq_invoice_charge_type'),
        ),
    ]
