# Generated by Django 5.2.10 on 2026-03-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0004_whpallet_ended_at_whpallet_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whbillingcharge',
            name='invoiced',
            field=models.BooleanField(default=False),
        ),
    ]
