# Generated by Django 5.2.10 on 2026-03-05 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0005_whbillingcharge_invoiced'),
    ]

    operations = [
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='storage_min_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_min_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
