# Generated by Django 5.2.10 on 2026-03-05 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0006_whcontacttariffoverride_storage_min_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whcontacttariffoverride',
            old_name='inbound_per_line',
            new_name='storage_per_m2_per_day',
        ),
        migrations.RenameField(
            model_name='whcontacttariffoverride',
            old_name='outbound_per_line',
            new_name='storage_per_m3_per_day',
        ),
        migrations.RenameField(
            model_name='whcontacttariffoverride',
            old_name='outbound_per_order',
            new_name='storage_per_pallet_per_day',
        ),
    ]
