# Generated by Django 5.2.10 on 2026-03-05 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0007_rename_inbound_per_line_whcontacttariffoverride_storage_per_m2_per_day_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='whcontacttariffoverride',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('storage_mode', 'pallet'), ('storage_per_pallet_per_day__isnull', False)), models.Q(('storage_mode', 'unit'), ('storage_per_unit_per_day__isnull', False)), models.Q(('storage_mode', 'm2'), ('storage_per_m2_per_day__isnull', False)), models.Q(('storage_mode', 'volume'), ('storage_per_m3_per_day__isnull', False)), _connector='OR'), name='valid_storage_override_mode_price'),
        ),
    ]
