# Generated by Django 5.2.10 on 2026-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0008_whcontacttariffoverride_valid_storage_override_mode_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='inbound_per_line',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='outbound_per_order',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
