# Generated by Django 5.2.10 on 2026-03-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0009_whcontacttariffoverride_inbound_per_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='outbound_per_line',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
