# Generated by Django 5.2.10 on 2026-03-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0010_whcontacttariffoverride_outbound_per_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='whinboundline',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='whinboundline',
            name='pallets',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='whinboundline',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='whinboundline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
