# Generated by Django 5.2.10 on 2026-03-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0011_whinboundline_area_m2_whinboundline_pallets_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whinboundline',
            name='chk_inboundline_qty_gt_0',
        ),
        migrations.AddConstraint(
            model_name='whinboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('pallets__gt', 0), ('area_m2__gt', 0), ('volume_m3__gt', 0), _connector='OR'), name='chk_inboundline_measurement_gt_0'),
        ),
    ]
