# Generated by Django 5.2.10 on 2026-03-06 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0012_remove_whinboundline_chk_inboundline_qty_gt_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whoutboundline',
            name='area_m2',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='whoutboundline',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='logistic.whlocation'),
        ),
        migrations.AddField(
            model_name='whoutboundline',
            name='pallets',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='whoutboundline',
            name='volume_m3',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='whoutboundline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True),
        ),
    ]
