# Generated by Django 5.2.10 on 2026-03-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0013_whoutboundline_area_m2_whoutboundline_location_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whoutboundline',
            name='chk_outboundline_qty_gt_0',
        ),
        migrations.AddConstraint(
            model_name='whoutboundline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('pallets__gt', 0), ('area_m2__gt', 0), ('volume_m3__gt', 0), _connector='OR'), name='chk_outboundline_measurement_gt_0'),
        ),
    ]
