# Generated by Django 5.2.10 on 2026-03-06 09:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('logistic', '0014_remove_whoutboundline_chk_outboundline_qty_gt_0_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whstockledger',
            name='chk_ledger_delta_nonzero',
        ),
        migrations.RemoveField(
            model_name='whstockledger',
            name='delta',
        ),
        migrations.AddField(
            model_name='whstock',
            name='area_m2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstock',
            name='pallets',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstock',
            name='volume_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='delta_area_m2',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='delta_pallets',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='delta_quantity',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='delta_volume_m3',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='is_reversed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='movement_direction',
            field=models.CharField(blank=True, choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='whstockledger',
            name='source_type',
            field=models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('adjustment', 'Adjustment'), ('transfer', 'Transfer')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='whstockledger',
            index=models.Index(fields=['company', 'product', 'location'], name='logistic_wh_company_ea245d_idx'),
        ),
        migrations.AddConstraint(
            model_name='whstockledger',
            constraint=models.CheckConstraint(condition=models.Q(('delta_quantity', 0), ('delta_pallets', 0), ('delta_area_m2', 0), ('delta_volume_m3', 0), _negated=True), name='chk_ledger_nonzero_movement'),
        ),
    ]
