# Generated by Django 5.2.10 on 2026-03-06 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0015_remove_whstockledger_chk_ledger_delta_nonzero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whbillingcharge',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.whlocation'),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistic.whproduct'),
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'm2'), ('m3', 'm3'), ('day', 'Day'), ('order', 'Order'), ('line', 'Line')], default='pallet', max_length=20),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='whbillingcharge',
            constraint=models.UniqueConstraint(fields=('company', 'source_model', 'source_uf', 'charge_type'), name='uniq_charge_source'),
        ),
    ]
