# Generated by Django 5.2.10 on 2026-03-06 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0016_whbillingcharge_location_whbillingcharge_locked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whstockledger',
            name='owner',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='att.contact'),
            preserve_default=False,
        ),
    ]
