# Generated by Django 5.2.10 on 2026-03-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_loadwarehouse_address_warehouse'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0017_whstockledger_owner'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whbillingcharge',
            name='uniq_charge_source',
        ),
        migrations.AddConstraint(
            model_name='whbillingcharge',
            constraint=models.UniqueConstraint(fields=('company', 'contact', 'billing_period', 'charge_type', 'source_model', 'source_uf'), name='uniq_charge_company_contact_period_source_type'),
        ),
    ]
