# Generated by Django 5.2.10 on 2026-03-06 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0018_remove_whbillingcharge_uniq_charge_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whbillinginvoice',
            name='uniq_invoice_company_contact_period',
        ),
    ]
