# Generated by Django 5.2.10 on 2026-03-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0019_remove_whbillinginvoice_uniq_invoice_company_contact_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whpalletmove',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='whpalletitem',
            name='pallet',
        ),
        migrations.RemoveField(
            model_name='whpalletitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='whpalletmove',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='whpalletmove',
            name='to_location',
        ),
        migrations.DeleteModel(
            name='WHPallet',
        ),
        migrations.DeleteModel(
            name='WHPalletItem',
        ),
        migrations.DeleteModel(
            name='WHPalletMove',
        ),
    ]
