# Generated by Django 5.2.10 on 2026-03-08 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0020_remove_whpalletmove_pallet_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whbillinginvoiceline',
            name='uniq_invoice_charge_type',
        ),
        migrations.AddConstraint(
            model_name='whbillinginvoiceline',
            constraint=models.UniqueConstraint(fields=('charge_type',), name='uniq_invoice_charge_type'),
        ),
    ]
