# Generated by Django 5.2.10 on 2026-03-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0021_remove_whbillinginvoiceline_uniq_invoice_charge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whbillingcharge',
            name='unit_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'm2'), ('m3', 'm3'), ('day', 'Day'), ('order', 'Order'), ('line', 'Line'), ('pallet_day', 'Pallet-Day'), ('unit_day', 'Unit-Day'), ('m2_day', 'm2-Day'), ('m3_day', 'm3-Day')], max_length=20),
        ),
    ]
