# Generated by Django 5.2.10 on 2026-03-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0022_alter_whbillingcharge_unit_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whbillinginvoiceline',
            name='uniq_invoice_charge_type',
        ),
    ]
