# Generated by Django 5.2.10 on 2026-03-12 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0023_remove_whbillinginvoiceline_uniq_invoice_charge_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whcontacttariffoverride',
            name='valid_storage_override_mode_price',
        ),
        migrations.RemoveConstraint(
            model_name='whstock',
            name='chk_stock_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='whstock',
            name='uniq_stock_company_owner_product_location',
        ),
        migrations.RenameField(
            model_name='whcontacttariffoverride',
            old_name='storage_per_pallet_per_day',
            new_name='storage_per_block_pallet_per_day',
        ),
        migrations.RenameField(
            model_name='whtariff',
            old_name='storage_per_pallet_per_day',
            new_name='storage_per_block_pallet_per_day',
        ),
        migrations.AddField(
            model_name='whbillingcharge',
            name='pallet_type',
            field=models.CharField(blank=True, choices=[('euro', 'Euro 120x80'), ('iso2', 'ISO2 120x100'), ('block', 'Block 120x120')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='storage_per_euro_pallet_per_day',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='storage_per_iso2_pallet_per_day',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='whinboundline',
            name='pallet_type',
            field=models.CharField(blank=True, choices=[('euro', 'Euro 120x80'), ('iso2', 'ISO2 120x100'), ('block', 'Block 120x120')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whoutboundline',
            name='pallet_type',
            field=models.CharField(blank=True, choices=[('euro', 'Euro 120x80'), ('iso2', 'ISO2 120x100'), ('block', 'Block 120x120')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whstock',
            name='pallet_type',
            field=models.CharField(blank=True, choices=[('euro', 'Euro 120x80'), ('iso2', 'ISO2 120x100'), ('block', 'Block 120x120')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whstockledger',
            name='pallet_type',
            field=models.CharField(blank=True, choices=[('euro', 'Euro 120x80'), ('iso2', 'ISO2 120x100'), ('block', 'Block 120x120')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_per_euro_pallet_per_day',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='whtariff',
            name='storage_per_iso2_pallet_per_day',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='whcontacttariffoverride',
            name='storage_mode',
            field=models.CharField(blank=True, choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'm2'), ('m3', 'm3')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='whoutbound',
            name='created_by_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_portal_wh_outbounds', to='logistic.whportalaccount'),
        ),
        migrations.AlterField(
            model_name='whtariff',
            name='storage_mode',
            field=models.CharField(choices=[('unit', 'Unit'), ('pallet', 'Pallet'), ('m2', 'm2'), ('m3', 'm3')], default='m2', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.UniqueConstraint(fields=('company', 'owner', 'product', 'location', 'pallet_type'), name='uniq_stock_company_owner_product_location_pallet_type'),
        ),
        migrations.AddConstraint(
            model_name='whstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0), ('pallets__gte', 0), ('area_m2__gte', 0), ('volume_m3__gte', 0)), name='chk_stock_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='whstockledger',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_user__isnull', False), ('actor_portal__isnull', True)), models.Q(('actor_user__isnull', True), ('actor_portal__isnull', False)), models.Q(('actor_user__isnull', True), ('actor_portal__isnull', True)), _connector='OR'), name='chk_stock_ledger_actor_one_or_none'),
        ),
    ]
