# Generated by Django 5.2.10 on 2026-03-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0024_remove_whcontacttariffoverride_valid_storage_override_mode_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='whbillingcharge',
            name='uniq_charge_company_contact_period_source_type',
        ),
        migrations.AddConstraint(
            model_name='whbillingcharge',
            constraint=models.UniqueConstraint(fields=('company', 'contact', 'billing_period', 'charge_type', 'source_model', 'source_uf', 'unit_type', 'pallet_type'), name='uniq_charge_company_contact_period_source_type_unit_pallet'),
        ),
    ]
