# Generated by Django 5.2.10 on 2026-03-12 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0025_remove_whbillingcharge_uniq_charge_company_contact_period_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whtariff',
            name='handling_tier_mode',
            field=models.CharField(choices=[('band', 'Band'), ('bracket', 'Bracket')], default='bracket', max_length=20),
        ),
        migrations.CreateModel(
            name='WHContactTariffHandlingTierOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('loading', 'Loading'), ('unloading', 'Unloading')], max_length=20)),
                ('unit', models.CharField(choices=[('pallet', 'Pallet'), ('m3', 'm3')], max_length=20)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('override', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_tier_overrides', to='logistic.whcontacttariffoverride')),
            ],
            options={
                'ordering': ['fee_type', 'unit', 'min_quantity', 'order'],
            },
        ),
        migrations.CreateModel(
            name='WHTariffHandlingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('loading', 'Loading'), ('unloading', 'Unloading')], max_length=20)),
                ('unit', models.CharField(choices=[('pallet', 'Pallet'), ('m3', 'm3')], max_length=20)),
                ('min_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handling_tiers', to='logistic.whtariff')),
            ],
            options={
                'ordering': ['fee_type', 'unit', 'min_quantity', 'order'],
                'constraints': [models.UniqueConstraint(fields=('tariff', 'fee_type', 'unit', 'min_quantity', 'max_quantity'), name='uniq_tariff_handling_tier_range')],
            },
        ),
    ]
