# Generated by Django 5.2.10 on 2026-03-12 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0026_whtariff_handling_tier_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='handling_tier_mode',
            field=models.CharField(blank=True, choices=[('band', 'Band'), ('bracket', 'Bracket')], max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='whcontacttariffhandlingtieroverride',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 0)), name='chk_tariff_handling_tier_override_min_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='whcontacttariffhandlingtieroverride',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gt', models.F('min_quantity')), _connector='OR'), name='chk_tariff_handling_tier_override_max_gt_min'),
        ),
        migrations.AddConstraint(
            model_name='whtariffhandlingtier',
            constraint=models.CheckConstraint(condition=models.Q(('min_quantity__gte', 0)), name='chk_tariff_handling_tier_min_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='whtariffhandlingtier',
            constraint=models.CheckConstraint(condition=models.Q(('max_quantity__isnull', True), ('max_quantity__gt', models.F('min_quantity')), _connector='OR'), name='chk_tariff_handling_tier_max_gt_min'),
        ),
    ]
