# Generated by Django 5.2.10 on 2026-03-13 04:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0027_whcontacttariffoverride_handling_tier_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='change_note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='whcontacttariffoverride',
            name='period_start',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='whcontacttariffoverride',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_wh_tariff_overrides', to='att.contact'),
        ),
    ]
