# Generated by Django 5.2.10 on 2026-03-13 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_remove_user_lync_key_sequence'),
        ('att', '0074_remove_contact_invoice_reference_date_and_more'),
        ('logistic', '0028_whcontacttariffoverride_change_note_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='whcontacttariffoverride',
            constraint=models.UniqueConstraint(fields=('company', 'contact', 'period_start'), name='uniq_wh_contact_tariff_override_start'),
        ),
    ]
