# Generated by Django 5.2.10 on 2026-03-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0029_whcontacttariffoverride_uniq_wh_contact_tariff_override_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whbillingcharge',
            name='charge_type',
            field=models.CharField(choices=[('storage', 'Storage'), ('handling_loading', 'Handling Loading'), ('handling_unloading', 'Handling Unloading'), ('inbound', 'Inbound'), ('outbound_order', 'Outbound Order'), ('outbound_line', 'Outbound Line')], max_length=30),
        ),
        migrations.AlterField(
            model_name='whbillinginvoiceline',
            name='charge_type',
            field=models.CharField(choices=[('storage', 'Storage'), ('handling_loading', 'Handling Loading'), ('handling_unloading', 'Handling Unloading'), ('inbound', 'Inbound'), ('outbound_order', 'Outbound Order'), ('outbound_line', 'Outbound Line')], max_length=30),
        ),
    ]
