# Generated by Django 5.2.10 on 2026-03-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0030_alter_whbillingcharge_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whbillinginvoiceline',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
