# Generated by Django 5.2.10 on 2026-03-19 09:19

import abb.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistic', '0033_whinboundcharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='WHOutboundCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36, unique=True)),
                ('charge_type', models.CharField(choices=[('outbound_per_order', 'Outbound per order'), ('outbound_per_line', 'Outbound per line'), ('handling_loading', 'Handling loading'), ('other', 'Other')], max_length=30)),
                ('label', models.CharField(max_length=120)),
                ('unit_type', models.CharField(choices=[('order', 'Order'), ('line', 'Line'), ('pallet', 'Pallet'), ('m3', 'm3'), ('unit', 'Unit'), ('fixed', 'Fixed')], default='fixed', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=18)),
                ('fee_type', models.CharField(blank=True, choices=[('loading', 'Loading'), ('unloading', 'Unloading')], max_length=20, null=True)),
                ('handling_unit', models.CharField(blank=True, choices=[('pallet', 'Pallet'), ('m3', 'm3')], max_length=20, null=True)),
                ('is_manual_price', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_charges', to='logistic.whoutbound')),
            ],
            options={
                'indexes': [models.Index(fields=['outbound'], name='logistic_wh_outboun_f20f49_idx'), models.Index(fields=['outbound', 'charge_type'], name='logistic_wh_outboun_3dd9cf_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='chk_wh_outbound_charge_qty_gt_0'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='chk_wh_outbound_charge_unit_price_gte_0')],
            },
        ),
    ]
