# Generated by Django 5.2.10 on 2026-02-20 11:59

import abb.utils
import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0033_remove_user_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uf', models.CharField(db_index=True, default=abb.utils.hex_uuid, max_length=36)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PARKING', 'Parking'), ('FUEL', 'Fuel station'), ('DINER', 'Diner/Restaurant'), ('SHOP', 'Shop/Supermarket'), ('SERVICE', 'Service/Repair'), ('WASH', 'Truck wash'), ('WEIGH', 'Weighbridge'), ('OTHER', 'Other')], db_index=True, max_length=20)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address_text', models.CharField(blank=True, default='', max_length=400)),
                ('osm_place_id', models.BigIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING', 'Pending review'), ('REJECTED', 'Rejected'), ('ARCHIVED', 'Archived')], db_index=True, default='PENDING', max_length=20)),
                ('visibility', models.CharField(choices=[('COMPANY', 'Company'), ('TEAM', 'Team'), ('PRIVATE', 'Private')], db_index=True, default='COMPANY', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('amenities', models.JSONField(blank=True, default=dict)),
                ('parking', models.JSONField(blank=True, default=dict)),
                ('pricing', models.JSONField(blank=True, default=dict)),
                ('pricing_last_updated_at', models.DateTimeField(blank=True, null=True)),
                ('has_wc', models.BooleanField(db_index=True, default=False)),
                ('has_shower', models.BooleanField(db_index=True, default=False)),
                ('has_diner', models.BooleanField(db_index=True, default=False)),
                ('has_shop', models.BooleanField(db_index=True, default=False)),
                ('has_fuel', models.BooleanField(db_index=True, default=False)),
                ('secure_level', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('UNSECURED', 'Unsecured'), ('FENCE_GATE', 'Fence/Gate'), ('CCTV', 'CCTV'), ('GUARDED', 'Guarded'), ('ACCESS_CONTROLLED', 'Access-controlled')], db_index=True, default='UNKNOWN', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_pois', to='app.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by_pois', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_by_pois', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='POIReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_overall', models.PositiveSmallIntegerField()),
                ('rating_security', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_cleanliness', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rating_value', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('visited_at', models.DateField(blank=True, null=True)),
                ('status_visible', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='auther_poi_reviews', to=settings.AUTH_USER_MODEL)),
                ('poi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poi_reviews', to='dpo.poi')),
            ],
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['point'], name='poi_point_gist_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=django.contrib.postgres.indexes.GinIndex(fields=['amenities'], name='poi_amenities_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=django.contrib.postgres.indexes.GinIndex(fields=['parking'], name='poi_parking_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=django.contrib.postgres.indexes.GinIndex(fields=['pricing'], name='poi_pricing_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='poi',
            index=models.Index(fields=['company', 'status', 'category'], name='poi_company_status_cat_idx'),
        ),
        migrations.AddConstraint(
            model_name='poi',
            constraint=models.UniqueConstraint(fields=('company', 'name', 'point'), name='poi_unique_name_point_per_company'),
        ),
        migrations.AddConstraint(
            model_name='poi',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='poi_name_not_empty'),
        ),
        migrations.AddIndex(
            model_name='poireview',
            index=models.Index(fields=['poi', 'status_visible', '-created_at'], name='poirev_poi_vis_created_idx'),
        ),
        migrations.AddIndex(
            model_name='poireview',
            index=models.Index(fields=['author', '-created_at'], name='poirev_author_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='poireview',
            constraint=models.CheckConstraint(condition=models.Q(('rating_overall__gte', 1), ('rating_overall__lte', 5)), name='poirev_overall_1_5'),
        ),
    ]
